site_name: Theopenem Documentation
theme: readthedocs

markdown_extensions:
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - attr_list
  - admonition
  - abbr
  - pymdownx.mark
  - pymdownx.magiclink
  - markdown_include.include:
      base_path: docs

nav:
- 'Welcome': index.md
- 'Getting Started':
  - 'Server Installation (Toems)': 
    - "Server Overview/Prereqs": getting-started/overview.md
    - "Install Toems Web Applications": getting-started/install-webapps.md
    - "Configure Theopenem": getting-started/configure.md  
    - "Update Web.config": getting-started/update-web-config.md
    - "Test Toec-API": getting-started/test-apps.md
    - "Install Certificates": getting-started/install-certificates.md
  - 'Client Installation (Toec)': 
    - "Endpoint Provisioning Setup": getting-started/endpoint-provisioning-setup.md
    - "Generate Toec Installer": getting-started/generate-toec-installer.md
    - "Install Toec": getting-started/install-toec.md
- 'Tutorials':
  - 'First Policy Tutorial': tutorials/first-policy.md
  - "Install Toec Via Group Policy": tutorials/deploy-toec.md
  - 'Toec Arguments': tutorials/toec-arguments.md
  - 'Update Procedure': tutorials/updates.md
  - 'How To Build The WIE': tutorials/wie.md
  - 'Logs': tutorials/logs.md
  
extra_css: [style.css]