### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.ProcessInventoryController
  commentId: T:Toems_ApplicationApi.Controllers.ProcessInventoryController
  id: ProcessInventoryController
  parent: Toems_ApplicationApi.Controllers
  children:
  - Toems_ApplicationApi.Controllers.ProcessInventoryController.#ctor
  - Toems_ApplicationApi.Controllers.ProcessInventoryController.Get
  - Toems_ApplicationApi.Controllers.ProcessInventoryController.Get(System.Int32)
  - Toems_ApplicationApi.Controllers.ProcessInventoryController.GetCount
  - Toems_ApplicationApi.Controllers.ProcessInventoryController.Search(Toems_Common.Dto.DtoSearchFilter)
  langs:
  - csharp
  - vb
  name: ProcessInventoryController
  nameWithType: ProcessInventoryController
  fullName: Toems_ApplicationApi.Controllers.ProcessInventoryController
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: 'public class ProcessInventoryController : ApiController'
    content.vb: Public Class ProcessInventoryController Inherits ApiController
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.Controllers.ProcessInventoryController.#ctor
  commentId: M:Toems_ApplicationApi.Controllers.ProcessInventoryController.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.Controllers.ProcessInventoryController
  langs:
  - csharp
  - vb
  name: ProcessInventoryController()
  nameWithType: ProcessInventoryController.ProcessInventoryController()
  fullName: Toems_ApplicationApi.Controllers.ProcessInventoryController.ProcessInventoryController()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public ProcessInventoryController()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.Controllers.ProcessInventoryController.#ctor*
  nameWithType.vb: ProcessInventoryController.New()
  fullName.vb: Toems_ApplicationApi.Controllers.ProcessInventoryController.New()
  name.vb: New()
- uid: Toems_ApplicationApi.Controllers.ProcessInventoryController.Get(System.Int32)
  commentId: M:Toems_ApplicationApi.Controllers.ProcessInventoryController.Get(System.Int32)
  id: Get(System.Int32)
  parent: Toems_ApplicationApi.Controllers.ProcessInventoryController
  langs:
  - csharp
  - vb
  name: Get(int)
  nameWithType: ProcessInventoryController.Get(int)
  fullName: Toems_ApplicationApi.Controllers.ProcessInventoryController.Get(int)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "reportRead")]

      public EntityProcessInventory Get(int id)
    parameters:
    - id: id
      type: System.Int32
    return:
      type: Toems_Common.Entity.EntityProcessInventory
    content.vb: >-
      <CustomAuth(Permission:="reportRead")>

      Public Function [Get](id As Integer) As EntityProcessInventory
  overload: Toems_ApplicationApi.Controllers.ProcessInventoryController.Get*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: reportRead
  nameWithType.vb: ProcessInventoryController.Get(Integer)
  fullName.vb: Toems_ApplicationApi.Controllers.ProcessInventoryController.Get(Integer)
  name.vb: Get(Integer)
- uid: Toems_ApplicationApi.Controllers.ProcessInventoryController.Get
  commentId: M:Toems_ApplicationApi.Controllers.ProcessInventoryController.Get
  id: Get
  parent: Toems_ApplicationApi.Controllers.ProcessInventoryController
  langs:
  - csharp
  - vb
  name: Get()
  nameWithType: ProcessInventoryController.Get()
  fullName: Toems_ApplicationApi.Controllers.ProcessInventoryController.Get()
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "reportRead")]

      public IEnumerable<EntityProcessInventory> Get()
    return:
      type: System.Collections.Generic.IEnumerable{Toems_Common.Entity.EntityProcessInventory}
    content.vb: >-
      <CustomAuth(Permission:="reportRead")>

      Public Function [Get]() As IEnumerable(Of EntityProcessInventory)
  overload: Toems_ApplicationApi.Controllers.ProcessInventoryController.Get*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: reportRead
- uid: Toems_ApplicationApi.Controllers.ProcessInventoryController.Search(Toems_Common.Dto.DtoSearchFilter)
  commentId: M:Toems_ApplicationApi.Controllers.ProcessInventoryController.Search(Toems_Common.Dto.DtoSearchFilter)
  id: Search(Toems_Common.Dto.DtoSearchFilter)
  parent: Toems_ApplicationApi.Controllers.ProcessInventoryController
  langs:
  - csharp
  - vb
  name: Search(DtoSearchFilter)
  nameWithType: ProcessInventoryController.Search(DtoSearchFilter)
  fullName: Toems_ApplicationApi.Controllers.ProcessInventoryController.Search(Toems_Common.Dto.DtoSearchFilter)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "reportRead")]

      public IEnumerable<EntityProcessInventory> Search(DtoSearchFilter filter)
    parameters:
    - id: filter
      type: Toems_Common.Dto.DtoSearchFilter
    return:
      type: System.Collections.Generic.IEnumerable{Toems_Common.Entity.EntityProcessInventory}
    content.vb: >-
      <CustomAuth(Permission:="reportRead")>

      Public Function Search(filter As DtoSearchFilter) As IEnumerable(Of EntityProcessInventory)
  overload: Toems_ApplicationApi.Controllers.ProcessInventoryController.Search*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: reportRead
- uid: Toems_ApplicationApi.Controllers.ProcessInventoryController.GetCount
  commentId: M:Toems_ApplicationApi.Controllers.ProcessInventoryController.GetCount
  id: GetCount
  parent: Toems_ApplicationApi.Controllers.ProcessInventoryController
  langs:
  - csharp
  - vb
  name: GetCount()
  nameWithType: ProcessInventoryController.GetCount()
  fullName: Toems_ApplicationApi.Controllers.ProcessInventoryController.GetCount()
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "reportRead")]

      public DtoApiStringResponse GetCount()
    return:
      type: Toems_Common.Dto.DtoApiStringResponse
    content.vb: >-
      <CustomAuth(Permission:="reportRead")>

      Public Function GetCount() As DtoApiStringResponse
  overload: Toems_ApplicationApi.Controllers.ProcessInventoryController.GetCount*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: reportRead
references:
- uid: Toems_ApplicationApi.Controllers
  commentId: N:Toems_ApplicationApi.Controllers
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers
  nameWithType: Toems_ApplicationApi.Controllers
  fullName: Toems_ApplicationApi.Controllers
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.Controllers.ProcessInventoryController.#ctor*
  commentId: Overload:Toems_ApplicationApi.Controllers.ProcessInventoryController.#ctor
  isExternal: true
  href: Toems_ApplicationApi.Controllers.ProcessInventoryController.html#Toems_ApplicationApi.Controllers.ProcessInventoryController.#ctor
  name: ProcessInventoryController
  nameWithType: ProcessInventoryController.ProcessInventoryController
  fullName: Toems_ApplicationApi.Controllers.ProcessInventoryController.ProcessInventoryController
  nameWithType.vb: ProcessInventoryController.New
  fullName.vb: Toems_ApplicationApi.Controllers.ProcessInventoryController.New
  name.vb: New
- uid: Toems_ApplicationApi.Controllers.ProcessInventoryController.Get*
  commentId: Overload:Toems_ApplicationApi.Controllers.ProcessInventoryController.Get
  isExternal: true
  href: Toems_ApplicationApi.Controllers.ProcessInventoryController.html#Toems_ApplicationApi.Controllers.ProcessInventoryController.Get(System.Int32)
  name: Get
  nameWithType: ProcessInventoryController.Get
  fullName: Toems_ApplicationApi.Controllers.ProcessInventoryController.Get
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Toems_Common.Entity.EntityProcessInventory
  commentId: '!:Toems_Common.Entity.EntityProcessInventory'
  isExternal: true
  name: EntityProcessInventory
  nameWithType: EntityProcessInventory
  fullName: Toems_Common.Entity.EntityProcessInventory
- uid: System.Collections.Generic.IEnumerable{Toems_Common.Entity.EntityProcessInventory}
  commentId: T:System.Collections.Generic.IEnumerable{Toems_Common.Entity.EntityProcessInventory}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<EntityProcessInventory>
  nameWithType: IEnumerable<EntityProcessInventory>
  fullName: System.Collections.Generic.IEnumerable<Toems_Common.Entity.EntityProcessInventory>
  nameWithType.vb: IEnumerable(Of EntityProcessInventory)
  fullName.vb: System.Collections.Generic.IEnumerable(Of Toems_Common.Entity.EntityProcessInventory)
  name.vb: IEnumerable(Of EntityProcessInventory)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - uid: Toems_Common.Entity.EntityProcessInventory
    name: EntityProcessInventory
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - uid: Toems_Common.Entity.EntityProcessInventory
    name: EntityProcessInventory
    isExternal: true
  - name: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Toems_ApplicationApi.Controllers.ProcessInventoryController.Search*
  commentId: Overload:Toems_ApplicationApi.Controllers.ProcessInventoryController.Search
  isExternal: true
  href: Toems_ApplicationApi.Controllers.ProcessInventoryController.html#Toems_ApplicationApi.Controllers.ProcessInventoryController.Search(Toems_Common.Dto.DtoSearchFilter)
  name: Search
  nameWithType: ProcessInventoryController.Search
  fullName: Toems_ApplicationApi.Controllers.ProcessInventoryController.Search
- uid: Toems_Common.Dto.DtoSearchFilter
  isExternal: true
  name: DtoSearchFilter
  nameWithType: DtoSearchFilter
  fullName: Toems_Common.Dto.DtoSearchFilter
- uid: Toems_ApplicationApi.Controllers.ProcessInventoryController.GetCount*
  commentId: Overload:Toems_ApplicationApi.Controllers.ProcessInventoryController.GetCount
  isExternal: true
  href: Toems_ApplicationApi.Controllers.ProcessInventoryController.html#Toems_ApplicationApi.Controllers.ProcessInventoryController.GetCount
  name: GetCount
  nameWithType: ProcessInventoryController.GetCount
  fullName: Toems_ApplicationApi.Controllers.ProcessInventoryController.GetCount
- uid: Toems_Common.Dto.DtoApiStringResponse
  isExternal: true
  name: DtoApiStringResponse
  nameWithType: DtoApiStringResponse
  fullName: Toems_Common.Dto.DtoApiStringResponse
