### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.VersionController
  commentId: T:Toems_ApplicationApi.Controllers.VersionController
  id: VersionController
  parent: Toems_ApplicationApi.Controllers
  children:
  - Toems_ApplicationApi.Controllers.VersionController.#ctor
  - Toems_ApplicationApi.Controllers.VersionController.Get(System.Int32)
  - Toems_ApplicationApi.Controllers.VersionController.GetAllVersionInfo
  - Toems_ApplicationApi.Controllers.VersionController.IsFirstRunCompleted
  - Toems_ApplicationApi.Controllers.VersionController.Put(System.Int32,Toems_Common.Entity.EntityVersion)
  - Toems_ApplicationApi.Controllers.VersionController.UpdateDatabase
  langs:
  - csharp
  - vb
  name: VersionController
  nameWithType: VersionController
  fullName: Toems_ApplicationApi.Controllers.VersionController
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: 'public class VersionController : ApiController'
    content.vb: Public Class VersionController Inherits ApiController
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.Controllers.VersionController.#ctor
  commentId: M:Toems_ApplicationApi.Controllers.VersionController.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.Controllers.VersionController
  langs:
  - csharp
  - vb
  name: VersionController()
  nameWithType: VersionController.VersionController()
  fullName: Toems_ApplicationApi.Controllers.VersionController.VersionController()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public VersionController()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.Controllers.VersionController.#ctor*
  nameWithType.vb: VersionController.New()
  fullName.vb: Toems_ApplicationApi.Controllers.VersionController.New()
  name.vb: New()
- uid: Toems_ApplicationApi.Controllers.VersionController.Get(System.Int32)
  commentId: M:Toems_ApplicationApi.Controllers.VersionController.Get(System.Int32)
  id: Get(System.Int32)
  parent: Toems_ApplicationApi.Controllers.VersionController
  langs:
  - csharp
  - vb
  name: Get(int)
  nameWithType: VersionController.Get(int)
  fullName: Toems_ApplicationApi.Controllers.VersionController.Get(int)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public EntityVersion Get(int id)
    parameters:
    - id: id
      type: System.Int32
    return:
      type: Toems_Common.Entity.EntityVersion
    content.vb: Public Function [Get](id As Integer) As EntityVersion
  overload: Toems_ApplicationApi.Controllers.VersionController.Get*
  nameWithType.vb: VersionController.Get(Integer)
  fullName.vb: Toems_ApplicationApi.Controllers.VersionController.Get(Integer)
  name.vb: Get(Integer)
- uid: Toems_ApplicationApi.Controllers.VersionController.IsFirstRunCompleted
  commentId: M:Toems_ApplicationApi.Controllers.VersionController.IsFirstRunCompleted
  id: IsFirstRunCompleted
  parent: Toems_ApplicationApi.Controllers.VersionController
  langs:
  - csharp
  - vb
  name: IsFirstRunCompleted()
  nameWithType: VersionController.IsFirstRunCompleted()
  fullName: Toems_ApplicationApi.Controllers.VersionController.IsFirstRunCompleted()
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public DtoApiBoolResponse IsFirstRunCompleted()
    return:
      type: Toems_Common.Dto.DtoApiBoolResponse
    content.vb: Public Function IsFirstRunCompleted() As DtoApiBoolResponse
  overload: Toems_ApplicationApi.Controllers.VersionController.IsFirstRunCompleted*
- uid: Toems_ApplicationApi.Controllers.VersionController.Put(System.Int32,Toems_Common.Entity.EntityVersion)
  commentId: M:Toems_ApplicationApi.Controllers.VersionController.Put(System.Int32,Toems_Common.Entity.EntityVersion)
  id: Put(System.Int32,Toems_Common.Entity.EntityVersion)
  parent: Toems_ApplicationApi.Controllers.VersionController
  langs:
  - csharp
  - vb
  name: Put(int, EntityVersion)
  nameWithType: VersionController.Put(int, EntityVersion)
  fullName: Toems_ApplicationApi.Controllers.VersionController.Put(int, Toems_Common.Entity.EntityVersion)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public DtoActionResult Put(int id, EntityVersion version)
    parameters:
    - id: id
      type: System.Int32
    - id: version
      type: Toems_Common.Entity.EntityVersion
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: Public Function Put(id As Integer, version As EntityVersion) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.VersionController.Put*
  nameWithType.vb: VersionController.Put(Integer, EntityVersion)
  fullName.vb: Toems_ApplicationApi.Controllers.VersionController.Put(Integer, Toems_Common.Entity.EntityVersion)
  name.vb: Put(Integer, EntityVersion)
- uid: Toems_ApplicationApi.Controllers.VersionController.GetAllVersionInfo
  commentId: M:Toems_ApplicationApi.Controllers.VersionController.GetAllVersionInfo
  id: GetAllVersionInfo
  parent: Toems_ApplicationApi.Controllers.VersionController
  langs:
  - csharp
  - vb
  name: GetAllVersionInfo()
  nameWithType: VersionController.GetAllVersionInfo()
  fullName: Toems_ApplicationApi.Controllers.VersionController.GetAllVersionInfo()
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public DtoVersion GetAllVersionInfo()
    return:
      type: Toems_Common.Dto.DtoVersion
    content.vb: Public Function GetAllVersionInfo() As DtoVersion
  overload: Toems_ApplicationApi.Controllers.VersionController.GetAllVersionInfo*
- uid: Toems_ApplicationApi.Controllers.VersionController.UpdateDatabase
  commentId: M:Toems_ApplicationApi.Controllers.VersionController.UpdateDatabase
  id: UpdateDatabase
  parent: Toems_ApplicationApi.Controllers.VersionController
  langs:
  - csharp
  - vb
  name: UpdateDatabase()
  nameWithType: VersionController.UpdateDatabase()
  fullName: Toems_ApplicationApi.Controllers.VersionController.UpdateDatabase()
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public DtoActionResult UpdateDatabase()
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: Public Function UpdateDatabase() As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.VersionController.UpdateDatabase*
references:
- uid: Toems_ApplicationApi.Controllers
  commentId: N:Toems_ApplicationApi.Controllers
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers
  nameWithType: Toems_ApplicationApi.Controllers
  fullName: Toems_ApplicationApi.Controllers
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.Controllers.VersionController.#ctor*
  commentId: Overload:Toems_ApplicationApi.Controllers.VersionController.#ctor
  isExternal: true
  href: Toems_ApplicationApi.Controllers.VersionController.html#Toems_ApplicationApi.Controllers.VersionController.#ctor
  name: VersionController
  nameWithType: VersionController.VersionController
  fullName: Toems_ApplicationApi.Controllers.VersionController.VersionController
  nameWithType.vb: VersionController.New
  fullName.vb: Toems_ApplicationApi.Controllers.VersionController.New
  name.vb: New
- uid: Toems_ApplicationApi.Controllers.VersionController.Get*
  commentId: Overload:Toems_ApplicationApi.Controllers.VersionController.Get
  isExternal: true
  href: Toems_ApplicationApi.Controllers.VersionController.html#Toems_ApplicationApi.Controllers.VersionController.Get(System.Int32)
  name: Get
  nameWithType: VersionController.Get
  fullName: Toems_ApplicationApi.Controllers.VersionController.Get
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Toems_Common.Entity.EntityVersion
  isExternal: true
  name: EntityVersion
  nameWithType: EntityVersion
  fullName: Toems_Common.Entity.EntityVersion
- uid: Toems_ApplicationApi.Controllers.VersionController.IsFirstRunCompleted*
  commentId: Overload:Toems_ApplicationApi.Controllers.VersionController.IsFirstRunCompleted
  isExternal: true
  href: Toems_ApplicationApi.Controllers.VersionController.html#Toems_ApplicationApi.Controllers.VersionController.IsFirstRunCompleted
  name: IsFirstRunCompleted
  nameWithType: VersionController.IsFirstRunCompleted
  fullName: Toems_ApplicationApi.Controllers.VersionController.IsFirstRunCompleted
- uid: Toems_Common.Dto.DtoApiBoolResponse
  isExternal: true
  name: DtoApiBoolResponse
  nameWithType: DtoApiBoolResponse
  fullName: Toems_Common.Dto.DtoApiBoolResponse
- uid: Toems_ApplicationApi.Controllers.VersionController.Put*
  commentId: Overload:Toems_ApplicationApi.Controllers.VersionController.Put
  isExternal: true
  href: Toems_ApplicationApi.Controllers.VersionController.html#Toems_ApplicationApi.Controllers.VersionController.Put(System.Int32,Toems_Common.Entity.EntityVersion)
  name: Put
  nameWithType: VersionController.Put
  fullName: Toems_ApplicationApi.Controllers.VersionController.Put
- uid: Toems_Common.Dto.DtoActionResult
  isExternal: true
  name: DtoActionResult
  nameWithType: DtoActionResult
  fullName: Toems_Common.Dto.DtoActionResult
- uid: Toems_ApplicationApi.Controllers.VersionController.GetAllVersionInfo*
  commentId: Overload:Toems_ApplicationApi.Controllers.VersionController.GetAllVersionInfo
  isExternal: true
  href: Toems_ApplicationApi.Controllers.VersionController.html#Toems_ApplicationApi.Controllers.VersionController.GetAllVersionInfo
  name: GetAllVersionInfo
  nameWithType: VersionController.GetAllVersionInfo
  fullName: Toems_ApplicationApi.Controllers.VersionController.GetAllVersionInfo
- uid: Toems_Common.Dto.DtoVersion
  commentId: '!:Toems_Common.Dto.DtoVersion'
  isExternal: true
  name: DtoVersion
  nameWithType: DtoVersion
  fullName: Toems_Common.Dto.DtoVersion
- uid: Toems_ApplicationApi.Controllers.VersionController.UpdateDatabase*
  commentId: Overload:Toems_ApplicationApi.Controllers.VersionController.UpdateDatabase
  isExternal: true
  href: Toems_ApplicationApi.Controllers.VersionController.html#Toems_ApplicationApi.Controllers.VersionController.UpdateDatabase
  name: UpdateDatabase
  nameWithType: VersionController.UpdateDatabase
  fullName: Toems_ApplicationApi.Controllers.VersionController.UpdateDatabase
