### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.UploadedFileController
  commentId: T:Toems_ApplicationApi.Controllers.UploadedFileController
  id: UploadedFileController
  parent: Toems_ApplicationApi.Controllers
  children:
  - Toems_ApplicationApi.Controllers.UploadedFileController.#ctor
  - Toems_ApplicationApi.Controllers.UploadedFileController.Delete(System.Int32)
  - Toems_ApplicationApi.Controllers.UploadedFileController.Get
  - Toems_ApplicationApi.Controllers.UploadedFileController.Get(System.Int32)
  - Toems_ApplicationApi.Controllers.UploadedFileController.GetCount
  - Toems_ApplicationApi.Controllers.UploadedFileController.GetModuleFiles(System.String)
  - Toems_ApplicationApi.Controllers.UploadedFileController.Search(Toems_Common.Dto.DtoSearchFilter)
  langs:
  - csharp
  - vb
  name: UploadedFileController
  nameWithType: UploadedFileController
  fullName: Toems_ApplicationApi.Controllers.UploadedFileController
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: 'public class UploadedFileController : ApiController'
    content.vb: Public Class UploadedFileController Inherits ApiController
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.Controllers.UploadedFileController.#ctor
  commentId: M:Toems_ApplicationApi.Controllers.UploadedFileController.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.Controllers.UploadedFileController
  langs:
  - csharp
  - vb
  name: UploadedFileController()
  nameWithType: UploadedFileController.UploadedFileController()
  fullName: Toems_ApplicationApi.Controllers.UploadedFileController.UploadedFileController()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public UploadedFileController()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.Controllers.UploadedFileController.#ctor*
  nameWithType.vb: UploadedFileController.New()
  fullName.vb: Toems_ApplicationApi.Controllers.UploadedFileController.New()
  name.vb: New()
- uid: Toems_ApplicationApi.Controllers.UploadedFileController.Delete(System.Int32)
  commentId: M:Toems_ApplicationApi.Controllers.UploadedFileController.Delete(System.Int32)
  id: Delete(System.Int32)
  parent: Toems_ApplicationApi.Controllers.UploadedFileController
  langs:
  - csharp
  - vb
  name: Delete(int)
  nameWithType: UploadedFileController.Delete(int)
  fullName: Toems_ApplicationApi.Controllers.UploadedFileController.Delete(int)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "moduleUpdate")]

      public DtoActionResult Delete(int id)
    parameters:
    - id: id
      type: System.Int32
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="moduleUpdate")>

      Public Function Delete(id As Integer) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.UploadedFileController.Delete*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: moduleUpdate
  nameWithType.vb: UploadedFileController.Delete(Integer)
  fullName.vb: Toems_ApplicationApi.Controllers.UploadedFileController.Delete(Integer)
  name.vb: Delete(Integer)
- uid: Toems_ApplicationApi.Controllers.UploadedFileController.Get(System.Int32)
  commentId: M:Toems_ApplicationApi.Controllers.UploadedFileController.Get(System.Int32)
  id: Get(System.Int32)
  parent: Toems_ApplicationApi.Controllers.UploadedFileController
  langs:
  - csharp
  - vb
  name: Get(int)
  nameWithType: UploadedFileController.Get(int)
  fullName: Toems_ApplicationApi.Controllers.UploadedFileController.Get(int)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "moduleRead")]

      public EntityUploadedFile Get(int id)
    parameters:
    - id: id
      type: System.Int32
    return:
      type: Toems_Common.Entity.EntityUploadedFile
    content.vb: >-
      <CustomAuth(Permission:="moduleRead")>

      Public Function [Get](id As Integer) As EntityUploadedFile
  overload: Toems_ApplicationApi.Controllers.UploadedFileController.Get*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: moduleRead
  nameWithType.vb: UploadedFileController.Get(Integer)
  fullName.vb: Toems_ApplicationApi.Controllers.UploadedFileController.Get(Integer)
  name.vb: Get(Integer)
- uid: Toems_ApplicationApi.Controllers.UploadedFileController.Get
  commentId: M:Toems_ApplicationApi.Controllers.UploadedFileController.Get
  id: Get
  parent: Toems_ApplicationApi.Controllers.UploadedFileController
  langs:
  - csharp
  - vb
  name: Get()
  nameWithType: UploadedFileController.Get()
  fullName: Toems_ApplicationApi.Controllers.UploadedFileController.Get()
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "moduleRead")]

      public IEnumerable<EntityUploadedFile> Get()
    return:
      type: System.Collections.Generic.IEnumerable{Toems_Common.Entity.EntityUploadedFile}
    content.vb: >-
      <CustomAuth(Permission:="moduleRead")>

      Public Function [Get]() As IEnumerable(Of EntityUploadedFile)
  overload: Toems_ApplicationApi.Controllers.UploadedFileController.Get*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: moduleRead
- uid: Toems_ApplicationApi.Controllers.UploadedFileController.Search(Toems_Common.Dto.DtoSearchFilter)
  commentId: M:Toems_ApplicationApi.Controllers.UploadedFileController.Search(Toems_Common.Dto.DtoSearchFilter)
  id: Search(Toems_Common.Dto.DtoSearchFilter)
  parent: Toems_ApplicationApi.Controllers.UploadedFileController
  langs:
  - csharp
  - vb
  name: Search(DtoSearchFilter)
  nameWithType: UploadedFileController.Search(DtoSearchFilter)
  fullName: Toems_ApplicationApi.Controllers.UploadedFileController.Search(Toems_Common.Dto.DtoSearchFilter)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "moduleRead")]

      public IEnumerable<EntityUploadedFile> Search(DtoSearchFilter filter)
    parameters:
    - id: filter
      type: Toems_Common.Dto.DtoSearchFilter
    return:
      type: System.Collections.Generic.IEnumerable{Toems_Common.Entity.EntityUploadedFile}
    content.vb: >-
      <CustomAuth(Permission:="moduleRead")>

      Public Function Search(filter As DtoSearchFilter) As IEnumerable(Of EntityUploadedFile)
  overload: Toems_ApplicationApi.Controllers.UploadedFileController.Search*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: moduleRead
- uid: Toems_ApplicationApi.Controllers.UploadedFileController.GetCount
  commentId: M:Toems_ApplicationApi.Controllers.UploadedFileController.GetCount
  id: GetCount
  parent: Toems_ApplicationApi.Controllers.UploadedFileController
  langs:
  - csharp
  - vb
  name: GetCount()
  nameWithType: UploadedFileController.GetCount()
  fullName: Toems_ApplicationApi.Controllers.UploadedFileController.GetCount()
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "moduleRead")]

      public DtoApiStringResponse GetCount()
    return:
      type: Toems_Common.Dto.DtoApiStringResponse
    content.vb: >-
      <CustomAuth(Permission:="moduleRead")>

      Public Function GetCount() As DtoApiStringResponse
  overload: Toems_ApplicationApi.Controllers.UploadedFileController.GetCount*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: moduleRead
- uid: Toems_ApplicationApi.Controllers.UploadedFileController.GetModuleFiles(System.String)
  commentId: M:Toems_ApplicationApi.Controllers.UploadedFileController.GetModuleFiles(System.String)
  id: GetModuleFiles(System.String)
  parent: Toems_ApplicationApi.Controllers.UploadedFileController
  langs:
  - csharp
  - vb
  name: GetModuleFiles(string)
  nameWithType: UploadedFileController.GetModuleFiles(string)
  fullName: Toems_ApplicationApi.Controllers.UploadedFileController.GetModuleFiles(string)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "moduleRead")]

      public IEnumerable<EntityUploadedFile> GetModuleFiles(string moduleGuid)
    parameters:
    - id: moduleGuid
      type: System.String
    return:
      type: System.Collections.Generic.IEnumerable{Toems_Common.Entity.EntityUploadedFile}
    content.vb: >-
      <CustomAuth(Permission:="moduleRead")>

      Public Function GetModuleFiles(moduleGuid As String) As IEnumerable(Of EntityUploadedFile)
  overload: Toems_ApplicationApi.Controllers.UploadedFileController.GetModuleFiles*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: moduleRead
  nameWithType.vb: UploadedFileController.GetModuleFiles(String)
  fullName.vb: Toems_ApplicationApi.Controllers.UploadedFileController.GetModuleFiles(String)
  name.vb: GetModuleFiles(String)
references:
- uid: Toems_ApplicationApi.Controllers
  commentId: N:Toems_ApplicationApi.Controllers
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers
  nameWithType: Toems_ApplicationApi.Controllers
  fullName: Toems_ApplicationApi.Controllers
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.Controllers.UploadedFileController.#ctor*
  commentId: Overload:Toems_ApplicationApi.Controllers.UploadedFileController.#ctor
  isExternal: true
  href: Toems_ApplicationApi.Controllers.UploadedFileController.html#Toems_ApplicationApi.Controllers.UploadedFileController.#ctor
  name: UploadedFileController
  nameWithType: UploadedFileController.UploadedFileController
  fullName: Toems_ApplicationApi.Controllers.UploadedFileController.UploadedFileController
  nameWithType.vb: UploadedFileController.New
  fullName.vb: Toems_ApplicationApi.Controllers.UploadedFileController.New
  name.vb: New
- uid: Toems_ApplicationApi.Controllers.UploadedFileController.Delete*
  commentId: Overload:Toems_ApplicationApi.Controllers.UploadedFileController.Delete
  isExternal: true
  href: Toems_ApplicationApi.Controllers.UploadedFileController.html#Toems_ApplicationApi.Controllers.UploadedFileController.Delete(System.Int32)
  name: Delete
  nameWithType: UploadedFileController.Delete
  fullName: Toems_ApplicationApi.Controllers.UploadedFileController.Delete
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Toems_Common.Dto.DtoActionResult
  isExternal: true
  name: DtoActionResult
  nameWithType: DtoActionResult
  fullName: Toems_Common.Dto.DtoActionResult
- uid: Toems_ApplicationApi.Controllers.UploadedFileController.Get*
  commentId: Overload:Toems_ApplicationApi.Controllers.UploadedFileController.Get
  isExternal: true
  href: Toems_ApplicationApi.Controllers.UploadedFileController.html#Toems_ApplicationApi.Controllers.UploadedFileController.Get(System.Int32)
  name: Get
  nameWithType: UploadedFileController.Get
  fullName: Toems_ApplicationApi.Controllers.UploadedFileController.Get
- uid: Toems_Common.Entity.EntityUploadedFile
  commentId: '!:Toems_Common.Entity.EntityUploadedFile'
  isExternal: true
  name: EntityUploadedFile
  nameWithType: EntityUploadedFile
  fullName: Toems_Common.Entity.EntityUploadedFile
- uid: System.Collections.Generic.IEnumerable{Toems_Common.Entity.EntityUploadedFile}
  commentId: T:System.Collections.Generic.IEnumerable{Toems_Common.Entity.EntityUploadedFile}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<EntityUploadedFile>
  nameWithType: IEnumerable<EntityUploadedFile>
  fullName: System.Collections.Generic.IEnumerable<Toems_Common.Entity.EntityUploadedFile>
  nameWithType.vb: IEnumerable(Of EntityUploadedFile)
  fullName.vb: System.Collections.Generic.IEnumerable(Of Toems_Common.Entity.EntityUploadedFile)
  name.vb: IEnumerable(Of EntityUploadedFile)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - uid: Toems_Common.Entity.EntityUploadedFile
    name: EntityUploadedFile
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - uid: Toems_Common.Entity.EntityUploadedFile
    name: EntityUploadedFile
    isExternal: true
  - name: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Toems_ApplicationApi.Controllers.UploadedFileController.Search*
  commentId: Overload:Toems_ApplicationApi.Controllers.UploadedFileController.Search
  isExternal: true
  href: Toems_ApplicationApi.Controllers.UploadedFileController.html#Toems_ApplicationApi.Controllers.UploadedFileController.Search(Toems_Common.Dto.DtoSearchFilter)
  name: Search
  nameWithType: UploadedFileController.Search
  fullName: Toems_ApplicationApi.Controllers.UploadedFileController.Search
- uid: Toems_Common.Dto.DtoSearchFilter
  isExternal: true
  name: DtoSearchFilter
  nameWithType: DtoSearchFilter
  fullName: Toems_Common.Dto.DtoSearchFilter
- uid: Toems_ApplicationApi.Controllers.UploadedFileController.GetCount*
  commentId: Overload:Toems_ApplicationApi.Controllers.UploadedFileController.GetCount
  isExternal: true
  href: Toems_ApplicationApi.Controllers.UploadedFileController.html#Toems_ApplicationApi.Controllers.UploadedFileController.GetCount
  name: GetCount
  nameWithType: UploadedFileController.GetCount
  fullName: Toems_ApplicationApi.Controllers.UploadedFileController.GetCount
- uid: Toems_Common.Dto.DtoApiStringResponse
  isExternal: true
  name: DtoApiStringResponse
  nameWithType: DtoApiStringResponse
  fullName: Toems_Common.Dto.DtoApiStringResponse
- uid: Toems_ApplicationApi.Controllers.UploadedFileController.GetModuleFiles*
  commentId: Overload:Toems_ApplicationApi.Controllers.UploadedFileController.GetModuleFiles
  isExternal: true
  href: Toems_ApplicationApi.Controllers.UploadedFileController.html#Toems_ApplicationApi.Controllers.UploadedFileController.GetModuleFiles(System.String)
  name: GetModuleFiles
  nameWithType: UploadedFileController.GetModuleFiles
  fullName: Toems_ApplicationApi.Controllers.UploadedFileController.GetModuleFiles
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
