### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.PinnedGroupController
  commentId: T:Toems_ApplicationApi.Controllers.PinnedGroupController
  id: PinnedGroupController
  parent: Toems_ApplicationApi.Controllers
  children:
  - Toems_ApplicationApi.Controllers.PinnedGroupController.#ctor
  - Toems_ApplicationApi.Controllers.PinnedGroupController.Delete(System.Int32,System.Int32)
  - Toems_ApplicationApi.Controllers.PinnedGroupController.Post(Toems_Common.Entity.EntityPinnedGroup)
  langs:
  - csharp
  - vb
  name: PinnedGroupController
  nameWithType: PinnedGroupController
  fullName: Toems_ApplicationApi.Controllers.PinnedGroupController
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: 'public class PinnedGroupController : ApiController'
    content.vb: Public Class PinnedGroupController Inherits ApiController
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.Controllers.PinnedGroupController.#ctor
  commentId: M:Toems_ApplicationApi.Controllers.PinnedGroupController.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.Controllers.PinnedGroupController
  langs:
  - csharp
  - vb
  name: PinnedGroupController()
  nameWithType: PinnedGroupController.PinnedGroupController()
  fullName: Toems_ApplicationApi.Controllers.PinnedGroupController.PinnedGroupController()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public PinnedGroupController()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.Controllers.PinnedGroupController.#ctor*
  nameWithType.vb: PinnedGroupController.New()
  fullName.vb: Toems_ApplicationApi.Controllers.PinnedGroupController.New()
  name.vb: New()
- uid: Toems_ApplicationApi.Controllers.PinnedGroupController.Delete(System.Int32,System.Int32)
  commentId: M:Toems_ApplicationApi.Controllers.PinnedGroupController.Delete(System.Int32,System.Int32)
  id: Delete(System.Int32,System.Int32)
  parent: Toems_ApplicationApi.Controllers.PinnedGroupController
  langs:
  - csharp
  - vb
  name: Delete(int, int)
  nameWithType: PinnedGroupController.Delete(int, int)
  fullName: Toems_ApplicationApi.Controllers.PinnedGroupController.Delete(int, int)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "groupRead")]

      public DtoActionResult Delete(int groupId, int userId)
    parameters:
    - id: groupId
      type: System.Int32
    - id: userId
      type: System.Int32
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="groupRead")>

      Public Function Delete(groupId As Integer, userId As Integer) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.PinnedGroupController.Delete*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: groupRead
  nameWithType.vb: PinnedGroupController.Delete(Integer, Integer)
  fullName.vb: Toems_ApplicationApi.Controllers.PinnedGroupController.Delete(Integer, Integer)
  name.vb: Delete(Integer, Integer)
- uid: Toems_ApplicationApi.Controllers.PinnedGroupController.Post(Toems_Common.Entity.EntityPinnedGroup)
  commentId: M:Toems_ApplicationApi.Controllers.PinnedGroupController.Post(Toems_Common.Entity.EntityPinnedGroup)
  id: Post(Toems_Common.Entity.EntityPinnedGroup)
  parent: Toems_ApplicationApi.Controllers.PinnedGroupController
  langs:
  - csharp
  - vb
  name: Post(EntityPinnedGroup)
  nameWithType: PinnedGroupController.Post(EntityPinnedGroup)
  fullName: Toems_ApplicationApi.Controllers.PinnedGroupController.Post(Toems_Common.Entity.EntityPinnedGroup)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "groupRead")]

      public DtoActionResult Post(EntityPinnedGroup pinnedGroup)
    parameters:
    - id: pinnedGroup
      type: Toems_Common.Entity.EntityPinnedGroup
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="groupRead")>

      Public Function Post(pinnedGroup As EntityPinnedGroup) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.PinnedGroupController.Post*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: groupRead
references:
- uid: Toems_ApplicationApi.Controllers
  commentId: N:Toems_ApplicationApi.Controllers
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers
  nameWithType: Toems_ApplicationApi.Controllers
  fullName: Toems_ApplicationApi.Controllers
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.Controllers.PinnedGroupController.#ctor*
  commentId: Overload:Toems_ApplicationApi.Controllers.PinnedGroupController.#ctor
  isExternal: true
  href: Toems_ApplicationApi.Controllers.PinnedGroupController.html#Toems_ApplicationApi.Controllers.PinnedGroupController.#ctor
  name: PinnedGroupController
  nameWithType: PinnedGroupController.PinnedGroupController
  fullName: Toems_ApplicationApi.Controllers.PinnedGroupController.PinnedGroupController
  nameWithType.vb: PinnedGroupController.New
  fullName.vb: Toems_ApplicationApi.Controllers.PinnedGroupController.New
  name.vb: New
- uid: Toems_ApplicationApi.Controllers.PinnedGroupController.Delete*
  commentId: Overload:Toems_ApplicationApi.Controllers.PinnedGroupController.Delete
  isExternal: true
  href: Toems_ApplicationApi.Controllers.PinnedGroupController.html#Toems_ApplicationApi.Controllers.PinnedGroupController.Delete(System.Int32,System.Int32)
  name: Delete
  nameWithType: PinnedGroupController.Delete
  fullName: Toems_ApplicationApi.Controllers.PinnedGroupController.Delete
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Toems_Common.Dto.DtoActionResult
  isExternal: true
  name: DtoActionResult
  nameWithType: DtoActionResult
  fullName: Toems_Common.Dto.DtoActionResult
- uid: Toems_ApplicationApi.Controllers.PinnedGroupController.Post*
  commentId: Overload:Toems_ApplicationApi.Controllers.PinnedGroupController.Post
  isExternal: true
  href: Toems_ApplicationApi.Controllers.PinnedGroupController.html#Toems_ApplicationApi.Controllers.PinnedGroupController.Post(Toems_Common.Entity.EntityPinnedGroup)
  name: Post
  nameWithType: PinnedGroupController.Post
  fullName: Toems_ApplicationApi.Controllers.PinnedGroupController.Post
- uid: Toems_Common.Entity.EntityPinnedGroup
  commentId: '!:Toems_Common.Entity.EntityPinnedGroup'
  isExternal: true
  name: EntityPinnedGroup
  nameWithType: EntityPinnedGroup
  fullName: Toems_Common.Entity.EntityPinnedGroup
