### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute
  commentId: T:Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute
  id: GroupAuthAttribute
  parent: Toems_ApplicationApi.Controllers.Authorization
  children:
  - Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.#ctor
  - Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.OnAuthorization(System.Web.Http.Controllers.HttpActionContext)
  langs:
  - csharp
  - vb
  name: GroupAuthAttribute
  nameWithType: GroupAuthAttribute
  fullName: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers.Authorization
  syntax:
    content: 'public class GroupAuthAttribute : AuthorizeAttribute'
    content.vb: Public Class GroupAuthAttribute Inherits AuthorizeAttribute
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.OnAuthorization(System.Web.Http.Controllers.HttpActionContext)
  commentId: M:Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.OnAuthorization(System.Web.Http.Controllers.HttpActionContext)
  id: OnAuthorization(System.Web.Http.Controllers.HttpActionContext)
  parent: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute
  langs:
  - csharp
  - vb
  name: OnAuthorization(HttpActionContext)
  nameWithType: GroupAuthAttribute.OnAuthorization(HttpActionContext)
  fullName: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.OnAuthorization(System.Web.Http.Controllers.HttpActionContext)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers.Authorization
  example: []
  syntax:
    content: public override void OnAuthorization(HttpActionContext actionContext)
    parameters:
    - id: actionContext
      type: System.Web.Http.Controllers.HttpActionContext
    content.vb: Public Overrides Sub OnAuthorization(actionContext As HttpActionContext)
  overload: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.OnAuthorization*
- uid: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.#ctor
  commentId: M:Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute
  langs:
  - csharp
  - vb
  name: GroupAuthAttribute()
  nameWithType: GroupAuthAttribute.GroupAuthAttribute()
  fullName: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.GroupAuthAttribute()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers.Authorization
  syntax:
    content: public GroupAuthAttribute()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.#ctor*
  nameWithType.vb: GroupAuthAttribute.New()
  fullName.vb: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.New()
  name.vb: New()
references:
- uid: Toems_ApplicationApi.Controllers.Authorization
  commentId: N:Toems_ApplicationApi.Controllers.Authorization
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers.Authorization
  nameWithType: Toems_ApplicationApi.Controllers.Authorization
  fullName: Toems_ApplicationApi.Controllers.Authorization
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers.Authorization
    name: Authorization
    isExternal: true
    href: Toems_ApplicationApi.Controllers.Authorization.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers.Authorization
    name: Authorization
    isExternal: true
    href: Toems_ApplicationApi.Controllers.Authorization.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.OnAuthorization*
  commentId: Overload:Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.OnAuthorization
  isExternal: true
  href: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.html#Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.OnAuthorization(System.Web.Http.Controllers.HttpActionContext)
  name: OnAuthorization
  nameWithType: GroupAuthAttribute.OnAuthorization
  fullName: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.OnAuthorization
- uid: System.Web.Http.Controllers.HttpActionContext
  isExternal: true
  name: HttpActionContext
  nameWithType: HttpActionContext
  fullName: System.Web.Http.Controllers.HttpActionContext
- uid: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.#ctor*
  commentId: Overload:Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.#ctor
  isExternal: true
  href: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.html#Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.#ctor
  name: GroupAuthAttribute
  nameWithType: GroupAuthAttribute.GroupAuthAttribute
  fullName: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.GroupAuthAttribute
  nameWithType.vb: GroupAuthAttribute.New
  fullName.vb: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.New
  name.vb: New
