### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController
  commentId: T:Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController
  id: SoftwareAssetSoftwareController
  parent: Toems_ApplicationApi.Controllers
  children:
  - Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.#ctor
  - Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Delete(System.Int32)
  - Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntitySoftwareAssetSoftware})
  langs:
  - csharp
  - vb
  name: SoftwareAssetSoftwareController
  nameWithType: SoftwareAssetSoftwareController
  fullName: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: 'public class SoftwareAssetSoftwareController : ApiController'
    content.vb: Public Class SoftwareAssetSoftwareController Inherits ApiController
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.#ctor
  commentId: M:Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController
  langs:
  - csharp
  - vb
  name: SoftwareAssetSoftwareController()
  nameWithType: SoftwareAssetSoftwareController.SoftwareAssetSoftwareController()
  fullName: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.SoftwareAssetSoftwareController()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public SoftwareAssetSoftwareController()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.#ctor*
  nameWithType.vb: SoftwareAssetSoftwareController.New()
  fullName.vb: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.New()
  name.vb: New()
- uid: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntitySoftwareAssetSoftware})
  commentId: M:Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntitySoftwareAssetSoftware})
  id: Post(System.Collections.Generic.List{Toems_Common.Entity.EntitySoftwareAssetSoftware})
  parent: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController
  langs:
  - csharp
  - vb
  name: Post(List<EntitySoftwareAssetSoftware>)
  nameWithType: SoftwareAssetSoftwareController.Post(List<EntitySoftwareAssetSoftware>)
  fullName: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Post(System.Collections.Generic.List<Toems_Common.Entity.EntitySoftwareAssetSoftware>)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "assetUpdate")]

      public DtoActionResult Post(List<EntitySoftwareAssetSoftware> software)
    parameters:
    - id: software
      type: System.Collections.Generic.List{Toems_Common.Entity.EntitySoftwareAssetSoftware}
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="assetUpdate")>

      Public Function Post(software As List(Of EntitySoftwareAssetSoftware)) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Post*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: assetUpdate
  nameWithType.vb: SoftwareAssetSoftwareController.Post(List(Of EntitySoftwareAssetSoftware))
  fullName.vb: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Post(System.Collections.Generic.List(Of Toems_Common.Entity.EntitySoftwareAssetSoftware))
  name.vb: Post(List(Of EntitySoftwareAssetSoftware))
- uid: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Delete(System.Int32)
  commentId: M:Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Delete(System.Int32)
  id: Delete(System.Int32)
  parent: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController
  langs:
  - csharp
  - vb
  name: Delete(int)
  nameWithType: SoftwareAssetSoftwareController.Delete(int)
  fullName: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Delete(int)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "assetUpdate")]

      public DtoActionResult Delete(int id)
    parameters:
    - id: id
      type: System.Int32
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="assetUpdate")>

      Public Function Delete(id As Integer) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Delete*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: assetUpdate
  nameWithType.vb: SoftwareAssetSoftwareController.Delete(Integer)
  fullName.vb: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Delete(Integer)
  name.vb: Delete(Integer)
references:
- uid: Toems_ApplicationApi.Controllers
  commentId: N:Toems_ApplicationApi.Controllers
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers
  nameWithType: Toems_ApplicationApi.Controllers
  fullName: Toems_ApplicationApi.Controllers
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.#ctor*
  commentId: Overload:Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.#ctor
  isExternal: true
  href: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.html#Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.#ctor
  name: SoftwareAssetSoftwareController
  nameWithType: SoftwareAssetSoftwareController.SoftwareAssetSoftwareController
  fullName: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.SoftwareAssetSoftwareController
  nameWithType.vb: SoftwareAssetSoftwareController.New
  fullName.vb: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.New
  name.vb: New
- uid: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Post*
  commentId: Overload:Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Post
  isExternal: true
  href: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.html#Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntitySoftwareAssetSoftware})
  name: Post
  nameWithType: SoftwareAssetSoftwareController.Post
  fullName: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Post
- uid: System.Collections.Generic.List{Toems_Common.Entity.EntitySoftwareAssetSoftware}
  commentId: T:System.Collections.Generic.List{Toems_Common.Entity.EntitySoftwareAssetSoftware}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<EntitySoftwareAssetSoftware>
  nameWithType: List<EntitySoftwareAssetSoftware>
  fullName: System.Collections.Generic.List<Toems_Common.Entity.EntitySoftwareAssetSoftware>
  nameWithType.vb: List(Of EntitySoftwareAssetSoftware)
  fullName.vb: System.Collections.Generic.List(Of Toems_Common.Entity.EntitySoftwareAssetSoftware)
  name.vb: List(Of EntitySoftwareAssetSoftware)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Toems_Common.Entity.EntitySoftwareAssetSoftware
    name: EntitySoftwareAssetSoftware
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Toems_Common.Entity.EntitySoftwareAssetSoftware
    name: EntitySoftwareAssetSoftware
    isExternal: true
  - name: )
- uid: Toems_Common.Dto.DtoActionResult
  isExternal: true
  name: DtoActionResult
  nameWithType: DtoActionResult
  fullName: Toems_Common.Dto.DtoActionResult
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Delete*
  commentId: Overload:Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Delete
  isExternal: true
  href: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.html#Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Delete(System.Int32)
  name: Delete
  nameWithType: SoftwareAssetSoftwareController.Delete
  fullName: Toems_ApplicationApi.Controllers.SoftwareAssetSoftwareController.Delete
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
