### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.CustomAuthenticationTokenProvider
  commentId: T:Toems_ApplicationApi.CustomAuthenticationTokenProvider
  id: CustomAuthenticationTokenProvider
  parent: Toems_ApplicationApi
  children:
  - Toems_ApplicationApi.CustomAuthenticationTokenProvider.#ctor
  - Toems_ApplicationApi.CustomAuthenticationTokenProvider.Receive(Microsoft.Owin.Security.Infrastructure.AuthenticationTokenReceiveContext)
  langs:
  - csharp
  - vb
  name: CustomAuthenticationTokenProvider
  nameWithType: CustomAuthenticationTokenProvider
  fullName: Toems_ApplicationApi.CustomAuthenticationTokenProvider
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi
  syntax:
    content: 'public class CustomAuthenticationTokenProvider : AuthenticationTokenProvider'
    content.vb: Public Class CustomAuthenticationTokenProvider Inherits AuthenticationTokenProvider
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.CustomAuthenticationTokenProvider.Receive(Microsoft.Owin.Security.Infrastructure.AuthenticationTokenReceiveContext)
  commentId: M:Toems_ApplicationApi.CustomAuthenticationTokenProvider.Receive(Microsoft.Owin.Security.Infrastructure.AuthenticationTokenReceiveContext)
  id: Receive(Microsoft.Owin.Security.Infrastructure.AuthenticationTokenReceiveContext)
  parent: Toems_ApplicationApi.CustomAuthenticationTokenProvider
  langs:
  - csharp
  - vb
  name: Receive(AuthenticationTokenReceiveContext)
  nameWithType: CustomAuthenticationTokenProvider.Receive(AuthenticationTokenReceiveContext)
  fullName: Toems_ApplicationApi.CustomAuthenticationTokenProvider.Receive(Microsoft.Owin.Security.Infrastructure.AuthenticationTokenReceiveContext)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi
  example: []
  syntax:
    content: public override void Receive(AuthenticationTokenReceiveContext context)
    parameters:
    - id: context
      type: Microsoft.Owin.Security.Infrastructure.AuthenticationTokenReceiveContext
    content.vb: Public Overrides Sub Receive(context As AuthenticationTokenReceiveContext)
  overload: Toems_ApplicationApi.CustomAuthenticationTokenProvider.Receive*
- uid: Toems_ApplicationApi.CustomAuthenticationTokenProvider.#ctor
  commentId: M:Toems_ApplicationApi.CustomAuthenticationTokenProvider.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.CustomAuthenticationTokenProvider
  langs:
  - csharp
  - vb
  name: CustomAuthenticationTokenProvider()
  nameWithType: CustomAuthenticationTokenProvider.CustomAuthenticationTokenProvider()
  fullName: Toems_ApplicationApi.CustomAuthenticationTokenProvider.CustomAuthenticationTokenProvider()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi
  syntax:
    content: public CustomAuthenticationTokenProvider()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.CustomAuthenticationTokenProvider.#ctor*
  nameWithType.vb: CustomAuthenticationTokenProvider.New()
  fullName.vb: Toems_ApplicationApi.CustomAuthenticationTokenProvider.New()
  name.vb: New()
references:
- uid: Toems_ApplicationApi
  commentId: N:Toems_ApplicationApi
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi
  nameWithType: Toems_ApplicationApi
  fullName: Toems_ApplicationApi
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.CustomAuthenticationTokenProvider.Receive*
  commentId: Overload:Toems_ApplicationApi.CustomAuthenticationTokenProvider.Receive
  isExternal: true
  href: Toems_ApplicationApi.CustomAuthenticationTokenProvider.html#Toems_ApplicationApi.CustomAuthenticationTokenProvider.Receive(Microsoft.Owin.Security.Infrastructure.AuthenticationTokenReceiveContext)
  name: Receive
  nameWithType: CustomAuthenticationTokenProvider.Receive
  fullName: Toems_ApplicationApi.CustomAuthenticationTokenProvider.Receive
- uid: Microsoft.Owin.Security.Infrastructure.AuthenticationTokenReceiveContext
  commentId: '!:Microsoft.Owin.Security.Infrastructure.AuthenticationTokenReceiveContext'
  isExternal: true
  name: AuthenticationTokenReceiveContext
  nameWithType: AuthenticationTokenReceiveContext
  fullName: Microsoft.Owin.Security.Infrastructure.AuthenticationTokenReceiveContext
- uid: Toems_ApplicationApi.CustomAuthenticationTokenProvider.#ctor*
  commentId: Overload:Toems_ApplicationApi.CustomAuthenticationTokenProvider.#ctor
  isExternal: true
  href: Toems_ApplicationApi.CustomAuthenticationTokenProvider.html#Toems_ApplicationApi.CustomAuthenticationTokenProvider.#ctor
  name: CustomAuthenticationTokenProvider
  nameWithType: CustomAuthenticationTokenProvider.CustomAuthenticationTokenProvider
  fullName: Toems_ApplicationApi.CustomAuthenticationTokenProvider.CustomAuthenticationTokenProvider
  nameWithType.vb: CustomAuthenticationTokenProvider.New
  fullName.vb: Toems_ApplicationApi.CustomAuthenticationTokenProvider.New
  name.vb: New
