### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.SimpleAuthorizationServerProvider
  commentId: T:Toems_ApplicationApi.SimpleAuthorizationServerProvider
  id: SimpleAuthorizationServerProvider
  parent: Toems_ApplicationApi
  children:
  - Toems_ApplicationApi.SimpleAuthorizationServerProvider.#ctor
  - Toems_ApplicationApi.SimpleAuthorizationServerProvider.GrantResourceOwnerCredentials(Microsoft.Owin.Security.OAuth.OAuthGrantResourceOwnerCredentialsContext)
  - Toems_ApplicationApi.SimpleAuthorizationServerProvider.ValidateClientAuthentication(Microsoft.Owin.Security.OAuth.OAuthValidateClientAuthenticationContext)
  langs:
  - csharp
  - vb
  name: SimpleAuthorizationServerProvider
  nameWithType: SimpleAuthorizationServerProvider
  fullName: Toems_ApplicationApi.SimpleAuthorizationServerProvider
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi
  syntax:
    content: 'public class SimpleAuthorizationServerProvider : OAuthAuthorizationServerProvider'
    content.vb: Public Class SimpleAuthorizationServerProvider Inherits OAuthAuthorizationServerProvider
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.SimpleAuthorizationServerProvider.GrantResourceOwnerCredentials(Microsoft.Owin.Security.OAuth.OAuthGrantResourceOwnerCredentialsContext)
  commentId: M:Toems_ApplicationApi.SimpleAuthorizationServerProvider.GrantResourceOwnerCredentials(Microsoft.Owin.Security.OAuth.OAuthGrantResourceOwnerCredentialsContext)
  id: GrantResourceOwnerCredentials(Microsoft.Owin.Security.OAuth.OAuthGrantResourceOwnerCredentialsContext)
  parent: Toems_ApplicationApi.SimpleAuthorizationServerProvider
  langs:
  - csharp
  - vb
  name: GrantResourceOwnerCredentials(OAuthGrantResourceOwnerCredentialsContext)
  nameWithType: SimpleAuthorizationServerProvider.GrantResourceOwnerCredentials(OAuthGrantResourceOwnerCredentialsContext)
  fullName: Toems_ApplicationApi.SimpleAuthorizationServerProvider.GrantResourceOwnerCredentials(Microsoft.Owin.Security.OAuth.OAuthGrantResourceOwnerCredentialsContext)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi
  example: []
  syntax:
    content: public override Task GrantResourceOwnerCredentials(OAuthGrantResourceOwnerCredentialsContext context)
    parameters:
    - id: context
      type: Microsoft.Owin.Security.OAuth.OAuthGrantResourceOwnerCredentialsContext
    return:
      type: System.Threading.Tasks.Task
    content.vb: Public Overrides Function GrantResourceOwnerCredentials(context As OAuthGrantResourceOwnerCredentialsContext) As Task
  overload: Toems_ApplicationApi.SimpleAuthorizationServerProvider.GrantResourceOwnerCredentials*
- uid: Toems_ApplicationApi.SimpleAuthorizationServerProvider.ValidateClientAuthentication(Microsoft.Owin.Security.OAuth.OAuthValidateClientAuthenticationContext)
  commentId: M:Toems_ApplicationApi.SimpleAuthorizationServerProvider.ValidateClientAuthentication(Microsoft.Owin.Security.OAuth.OAuthValidateClientAuthenticationContext)
  id: ValidateClientAuthentication(Microsoft.Owin.Security.OAuth.OAuthValidateClientAuthenticationContext)
  parent: Toems_ApplicationApi.SimpleAuthorizationServerProvider
  langs:
  - csharp
  - vb
  name: ValidateClientAuthentication(OAuthValidateClientAuthenticationContext)
  nameWithType: SimpleAuthorizationServerProvider.ValidateClientAuthentication(OAuthValidateClientAuthenticationContext)
  fullName: Toems_ApplicationApi.SimpleAuthorizationServerProvider.ValidateClientAuthentication(Microsoft.Owin.Security.OAuth.OAuthValidateClientAuthenticationContext)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi
  example: []
  syntax:
    content: public override Task ValidateClientAuthentication(OAuthValidateClientAuthenticationContext context)
    parameters:
    - id: context
      type: Microsoft.Owin.Security.OAuth.OAuthValidateClientAuthenticationContext
    return:
      type: System.Threading.Tasks.Task
    content.vb: Public Overrides Function ValidateClientAuthentication(context As OAuthValidateClientAuthenticationContext) As Task
  overload: Toems_ApplicationApi.SimpleAuthorizationServerProvider.ValidateClientAuthentication*
- uid: Toems_ApplicationApi.SimpleAuthorizationServerProvider.#ctor
  commentId: M:Toems_ApplicationApi.SimpleAuthorizationServerProvider.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.SimpleAuthorizationServerProvider
  langs:
  - csharp
  - vb
  name: SimpleAuthorizationServerProvider()
  nameWithType: SimpleAuthorizationServerProvider.SimpleAuthorizationServerProvider()
  fullName: Toems_ApplicationApi.SimpleAuthorizationServerProvider.SimpleAuthorizationServerProvider()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi
  syntax:
    content: public SimpleAuthorizationServerProvider()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.SimpleAuthorizationServerProvider.#ctor*
  nameWithType.vb: SimpleAuthorizationServerProvider.New()
  fullName.vb: Toems_ApplicationApi.SimpleAuthorizationServerProvider.New()
  name.vb: New()
references:
- uid: Toems_ApplicationApi
  commentId: N:Toems_ApplicationApi
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi
  nameWithType: Toems_ApplicationApi
  fullName: Toems_ApplicationApi
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.SimpleAuthorizationServerProvider.GrantResourceOwnerCredentials*
  commentId: Overload:Toems_ApplicationApi.SimpleAuthorizationServerProvider.GrantResourceOwnerCredentials
  isExternal: true
  href: Toems_ApplicationApi.SimpleAuthorizationServerProvider.html#Toems_ApplicationApi.SimpleAuthorizationServerProvider.GrantResourceOwnerCredentials(Microsoft.Owin.Security.OAuth.OAuthGrantResourceOwnerCredentialsContext)
  name: GrantResourceOwnerCredentials
  nameWithType: SimpleAuthorizationServerProvider.GrantResourceOwnerCredentials
  fullName: Toems_ApplicationApi.SimpleAuthorizationServerProvider.GrantResourceOwnerCredentials
- uid: Microsoft.Owin.Security.OAuth.OAuthGrantResourceOwnerCredentialsContext
  commentId: '!:Microsoft.Owin.Security.OAuth.OAuthGrantResourceOwnerCredentialsContext'
  isExternal: true
  name: OAuthGrantResourceOwnerCredentialsContext
  nameWithType: OAuthGrantResourceOwnerCredentialsContext
  fullName: Microsoft.Owin.Security.OAuth.OAuthGrantResourceOwnerCredentialsContext
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
- uid: Toems_ApplicationApi.SimpleAuthorizationServerProvider.ValidateClientAuthentication*
  commentId: Overload:Toems_ApplicationApi.SimpleAuthorizationServerProvider.ValidateClientAuthentication
  isExternal: true
  href: Toems_ApplicationApi.SimpleAuthorizationServerProvider.html#Toems_ApplicationApi.SimpleAuthorizationServerProvider.ValidateClientAuthentication(Microsoft.Owin.Security.OAuth.OAuthValidateClientAuthenticationContext)
  name: ValidateClientAuthentication
  nameWithType: SimpleAuthorizationServerProvider.ValidateClientAuthentication
  fullName: Toems_ApplicationApi.SimpleAuthorizationServerProvider.ValidateClientAuthentication
- uid: Microsoft.Owin.Security.OAuth.OAuthValidateClientAuthenticationContext
  commentId: '!:Microsoft.Owin.Security.OAuth.OAuthValidateClientAuthenticationContext'
  isExternal: true
  name: OAuthValidateClientAuthenticationContext
  nameWithType: OAuthValidateClientAuthenticationContext
  fullName: Microsoft.Owin.Security.OAuth.OAuthValidateClientAuthenticationContext
- uid: Toems_ApplicationApi.SimpleAuthorizationServerProvider.#ctor*
  commentId: Overload:Toems_ApplicationApi.SimpleAuthorizationServerProvider.#ctor
  isExternal: true
  href: Toems_ApplicationApi.SimpleAuthorizationServerProvider.html#Toems_ApplicationApi.SimpleAuthorizationServerProvider.#ctor
  name: SimpleAuthorizationServerProvider
  nameWithType: SimpleAuthorizationServerProvider.SimpleAuthorizationServerProvider
  fullName: Toems_ApplicationApi.SimpleAuthorizationServerProvider.SimpleAuthorizationServerProvider
  nameWithType.vb: SimpleAuthorizationServerProvider.New
  fullName.vb: Toems_ApplicationApi.SimpleAuthorizationServerProvider.New
  name.vb: New
