### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.ApprovalRequestController
  commentId: T:Toems_ApplicationApi.Controllers.ApprovalRequestController
  id: ApprovalRequestController
  parent: Toems_ApplicationApi.Controllers
  children:
  - Toems_ApplicationApi.Controllers.ApprovalRequestController.#ctor
  - Toems_ApplicationApi.Controllers.ApprovalRequestController.Approve(System.Int32)
  - Toems_ApplicationApi.Controllers.ApprovalRequestController.Delete(System.Int32)
  - Toems_ApplicationApi.Controllers.ApprovalRequestController.GetCount
  - Toems_ApplicationApi.Controllers.ApprovalRequestController.Search(Toems_Common.Dto.DtoSearchFilter)
  langs:
  - csharp
  - vb
  name: ApprovalRequestController
  nameWithType: ApprovalRequestController
  fullName: Toems_ApplicationApi.Controllers.ApprovalRequestController
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: 'public class ApprovalRequestController : ApiController'
    content.vb: Public Class ApprovalRequestController Inherits ApiController
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.Controllers.ApprovalRequestController.#ctor
  commentId: M:Toems_ApplicationApi.Controllers.ApprovalRequestController.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.Controllers.ApprovalRequestController
  langs:
  - csharp
  - vb
  name: ApprovalRequestController()
  nameWithType: ApprovalRequestController.ApprovalRequestController()
  fullName: Toems_ApplicationApi.Controllers.ApprovalRequestController.ApprovalRequestController()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public ApprovalRequestController()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.Controllers.ApprovalRequestController.#ctor*
  nameWithType.vb: ApprovalRequestController.New()
  fullName.vb: Toems_ApplicationApi.Controllers.ApprovalRequestController.New()
  name.vb: New()
- uid: Toems_ApplicationApi.Controllers.ApprovalRequestController.Delete(System.Int32)
  commentId: M:Toems_ApplicationApi.Controllers.ApprovalRequestController.Delete(System.Int32)
  id: Delete(System.Int32)
  parent: Toems_ApplicationApi.Controllers.ApprovalRequestController
  langs:
  - csharp
  - vb
  name: Delete(int)
  nameWithType: ApprovalRequestController.Delete(int)
  fullName: Toems_ApplicationApi.Controllers.ApprovalRequestController.Delete(int)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "approveProvision")]

      public DtoActionResult Delete(int id)
    parameters:
    - id: id
      type: System.Int32
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="approveProvision")>

      Public Function Delete(id As Integer) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.ApprovalRequestController.Delete*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: approveProvision
  nameWithType.vb: ApprovalRequestController.Delete(Integer)
  fullName.vb: Toems_ApplicationApi.Controllers.ApprovalRequestController.Delete(Integer)
  name.vb: Delete(Integer)
- uid: Toems_ApplicationApi.Controllers.ApprovalRequestController.Search(Toems_Common.Dto.DtoSearchFilter)
  commentId: M:Toems_ApplicationApi.Controllers.ApprovalRequestController.Search(Toems_Common.Dto.DtoSearchFilter)
  id: Search(Toems_Common.Dto.DtoSearchFilter)
  parent: Toems_ApplicationApi.Controllers.ApprovalRequestController
  langs:
  - csharp
  - vb
  name: Search(DtoSearchFilter)
  nameWithType: ApprovalRequestController.Search(DtoSearchFilter)
  fullName: Toems_ApplicationApi.Controllers.ApprovalRequestController.Search(Toems_Common.Dto.DtoSearchFilter)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "computerRead")]

      public IEnumerable<EntityApprovalRequest> Search(DtoSearchFilter filter)
    parameters:
    - id: filter
      type: Toems_Common.Dto.DtoSearchFilter
    return:
      type: System.Collections.Generic.IEnumerable{Toems_Common.Entity.EntityApprovalRequest}
    content.vb: >-
      <CustomAuth(Permission:="computerRead")>

      Public Function Search(filter As DtoSearchFilter) As IEnumerable(Of EntityApprovalRequest)
  overload: Toems_ApplicationApi.Controllers.ApprovalRequestController.Search*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: computerRead
- uid: Toems_ApplicationApi.Controllers.ApprovalRequestController.GetCount
  commentId: M:Toems_ApplicationApi.Controllers.ApprovalRequestController.GetCount
  id: GetCount
  parent: Toems_ApplicationApi.Controllers.ApprovalRequestController
  langs:
  - csharp
  - vb
  name: GetCount()
  nameWithType: ApprovalRequestController.GetCount()
  fullName: Toems_ApplicationApi.Controllers.ApprovalRequestController.GetCount()
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "computerRead")]

      public DtoApiStringResponse GetCount()
    return:
      type: Toems_Common.Dto.DtoApiStringResponse
    content.vb: >-
      <CustomAuth(Permission:="computerRead")>

      Public Function GetCount() As DtoApiStringResponse
  overload: Toems_ApplicationApi.Controllers.ApprovalRequestController.GetCount*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: computerRead
- uid: Toems_ApplicationApi.Controllers.ApprovalRequestController.Approve(System.Int32)
  commentId: M:Toems_ApplicationApi.Controllers.ApprovalRequestController.Approve(System.Int32)
  id: Approve(System.Int32)
  parent: Toems_ApplicationApi.Controllers.ApprovalRequestController
  langs:
  - csharp
  - vb
  name: Approve(int)
  nameWithType: ApprovalRequestController.Approve(int)
  fullName: Toems_ApplicationApi.Controllers.ApprovalRequestController.Approve(int)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "approveProvision")]

      public DtoActionResult Approve(int id)
    parameters:
    - id: id
      type: System.Int32
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="approveProvision")>

      Public Function Approve(id As Integer) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.ApprovalRequestController.Approve*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: approveProvision
  nameWithType.vb: ApprovalRequestController.Approve(Integer)
  fullName.vb: Toems_ApplicationApi.Controllers.ApprovalRequestController.Approve(Integer)
  name.vb: Approve(Integer)
references:
- uid: Toems_ApplicationApi.Controllers
  commentId: N:Toems_ApplicationApi.Controllers
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers
  nameWithType: Toems_ApplicationApi.Controllers
  fullName: Toems_ApplicationApi.Controllers
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.Controllers.ApprovalRequestController.#ctor*
  commentId: Overload:Toems_ApplicationApi.Controllers.ApprovalRequestController.#ctor
  isExternal: true
  href: Toems_ApplicationApi.Controllers.ApprovalRequestController.html#Toems_ApplicationApi.Controllers.ApprovalRequestController.#ctor
  name: ApprovalRequestController
  nameWithType: ApprovalRequestController.ApprovalRequestController
  fullName: Toems_ApplicationApi.Controllers.ApprovalRequestController.ApprovalRequestController
  nameWithType.vb: ApprovalRequestController.New
  fullName.vb: Toems_ApplicationApi.Controllers.ApprovalRequestController.New
  name.vb: New
- uid: Toems_ApplicationApi.Controllers.ApprovalRequestController.Delete*
  commentId: Overload:Toems_ApplicationApi.Controllers.ApprovalRequestController.Delete
  isExternal: true
  href: Toems_ApplicationApi.Controllers.ApprovalRequestController.html#Toems_ApplicationApi.Controllers.ApprovalRequestController.Delete(System.Int32)
  name: Delete
  nameWithType: ApprovalRequestController.Delete
  fullName: Toems_ApplicationApi.Controllers.ApprovalRequestController.Delete
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Toems_Common.Dto.DtoActionResult
  isExternal: true
  name: DtoActionResult
  nameWithType: DtoActionResult
  fullName: Toems_Common.Dto.DtoActionResult
- uid: Toems_ApplicationApi.Controllers.ApprovalRequestController.Search*
  commentId: Overload:Toems_ApplicationApi.Controllers.ApprovalRequestController.Search
  isExternal: true
  href: Toems_ApplicationApi.Controllers.ApprovalRequestController.html#Toems_ApplicationApi.Controllers.ApprovalRequestController.Search(Toems_Common.Dto.DtoSearchFilter)
  name: Search
  nameWithType: ApprovalRequestController.Search
  fullName: Toems_ApplicationApi.Controllers.ApprovalRequestController.Search
- uid: Toems_Common.Dto.DtoSearchFilter
  isExternal: true
  name: DtoSearchFilter
  nameWithType: DtoSearchFilter
  fullName: Toems_Common.Dto.DtoSearchFilter
- uid: System.Collections.Generic.IEnumerable{Toems_Common.Entity.EntityApprovalRequest}
  commentId: T:System.Collections.Generic.IEnumerable{Toems_Common.Entity.EntityApprovalRequest}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<EntityApprovalRequest>
  nameWithType: IEnumerable<EntityApprovalRequest>
  fullName: System.Collections.Generic.IEnumerable<Toems_Common.Entity.EntityApprovalRequest>
  nameWithType.vb: IEnumerable(Of EntityApprovalRequest)
  fullName.vb: System.Collections.Generic.IEnumerable(Of Toems_Common.Entity.EntityApprovalRequest)
  name.vb: IEnumerable(Of EntityApprovalRequest)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - uid: Toems_Common.Entity.EntityApprovalRequest
    name: EntityApprovalRequest
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - uid: Toems_Common.Entity.EntityApprovalRequest
    name: EntityApprovalRequest
    isExternal: true
  - name: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Toems_ApplicationApi.Controllers.ApprovalRequestController.GetCount*
  commentId: Overload:Toems_ApplicationApi.Controllers.ApprovalRequestController.GetCount
  isExternal: true
  href: Toems_ApplicationApi.Controllers.ApprovalRequestController.html#Toems_ApplicationApi.Controllers.ApprovalRequestController.GetCount
  name: GetCount
  nameWithType: ApprovalRequestController.GetCount
  fullName: Toems_ApplicationApi.Controllers.ApprovalRequestController.GetCount
- uid: Toems_Common.Dto.DtoApiStringResponse
  isExternal: true
  name: DtoApiStringResponse
  nameWithType: DtoApiStringResponse
  fullName: Toems_Common.Dto.DtoApiStringResponse
- uid: Toems_ApplicationApi.Controllers.ApprovalRequestController.Approve*
  commentId: Overload:Toems_ApplicationApi.Controllers.ApprovalRequestController.Approve
  isExternal: true
  href: Toems_ApplicationApi.Controllers.ApprovalRequestController.html#Toems_ApplicationApi.Controllers.ApprovalRequestController.Approve(System.Int32)
  name: Approve
  nameWithType: ApprovalRequestController.Approve
  fullName: Toems_ApplicationApi.Controllers.ApprovalRequestController.Approve
