### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.ComClusterServerController
  commentId: T:Toems_ApplicationApi.Controllers.ComClusterServerController
  id: ComClusterServerController
  parent: Toems_ApplicationApi.Controllers
  children:
  - Toems_ApplicationApi.Controllers.ComClusterServerController.#ctor
  - Toems_ApplicationApi.Controllers.ComClusterServerController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityComServerClusterServer})
  langs:
  - csharp
  - vb
  name: ComClusterServerController
  nameWithType: ComClusterServerController
  fullName: Toems_ApplicationApi.Controllers.ComClusterServerController
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: 'public class ComClusterServerController : ApiController'
    content.vb: Public Class ComClusterServerController Inherits ApiController
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.Controllers.ComClusterServerController.#ctor
  commentId: M:Toems_ApplicationApi.Controllers.ComClusterServerController.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.Controllers.ComClusterServerController
  langs:
  - csharp
  - vb
  name: ComClusterServerController()
  nameWithType: ComClusterServerController.ComClusterServerController()
  fullName: Toems_ApplicationApi.Controllers.ComClusterServerController.ComClusterServerController()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public ComClusterServerController()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.Controllers.ComClusterServerController.#ctor*
  nameWithType.vb: ComClusterServerController.New()
  fullName.vb: Toems_ApplicationApi.Controllers.ComClusterServerController.New()
  name.vb: New()
- uid: Toems_ApplicationApi.Controllers.ComClusterServerController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityComServerClusterServer})
  commentId: M:Toems_ApplicationApi.Controllers.ComClusterServerController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityComServerClusterServer})
  id: Post(System.Collections.Generic.List{Toems_Common.Entity.EntityComServerClusterServer})
  parent: Toems_ApplicationApi.Controllers.ComClusterServerController
  langs:
  - csharp
  - vb
  name: Post(List<EntityComServerClusterServer>)
  nameWithType: ComClusterServerController.Post(List<EntityComServerClusterServer>)
  fullName: Toems_ApplicationApi.Controllers.ComClusterServerController.Post(System.Collections.Generic.List<Toems_Common.Entity.EntityComServerClusterServer>)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "Administrator")]

      public DtoActionResult Post(List<EntityComServerClusterServer> listOfServers)
    parameters:
    - id: listOfServers
      type: System.Collections.Generic.List{Toems_Common.Entity.EntityComServerClusterServer}
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="Administrator")>

      Public Function Post(listOfServers As List(Of EntityComServerClusterServer)) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.ComClusterServerController.Post*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: Administrator
  nameWithType.vb: ComClusterServerController.Post(List(Of EntityComServerClusterServer))
  fullName.vb: Toems_ApplicationApi.Controllers.ComClusterServerController.Post(System.Collections.Generic.List(Of Toems_Common.Entity.EntityComServerClusterServer))
  name.vb: Post(List(Of EntityComServerClusterServer))
references:
- uid: Toems_ApplicationApi.Controllers
  commentId: N:Toems_ApplicationApi.Controllers
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers
  nameWithType: Toems_ApplicationApi.Controllers
  fullName: Toems_ApplicationApi.Controllers
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.Controllers.ComClusterServerController.#ctor*
  commentId: Overload:Toems_ApplicationApi.Controllers.ComClusterServerController.#ctor
  isExternal: true
  href: Toems_ApplicationApi.Controllers.ComClusterServerController.html#Toems_ApplicationApi.Controllers.ComClusterServerController.#ctor
  name: ComClusterServerController
  nameWithType: ComClusterServerController.ComClusterServerController
  fullName: Toems_ApplicationApi.Controllers.ComClusterServerController.ComClusterServerController
  nameWithType.vb: ComClusterServerController.New
  fullName.vb: Toems_ApplicationApi.Controllers.ComClusterServerController.New
  name.vb: New
- uid: Toems_ApplicationApi.Controllers.ComClusterServerController.Post*
  commentId: Overload:Toems_ApplicationApi.Controllers.ComClusterServerController.Post
  isExternal: true
  href: Toems_ApplicationApi.Controllers.ComClusterServerController.html#Toems_ApplicationApi.Controllers.ComClusterServerController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityComServerClusterServer})
  name: Post
  nameWithType: ComClusterServerController.Post
  fullName: Toems_ApplicationApi.Controllers.ComClusterServerController.Post
- uid: System.Collections.Generic.List{Toems_Common.Entity.EntityComServerClusterServer}
  commentId: T:System.Collections.Generic.List{Toems_Common.Entity.EntityComServerClusterServer}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<EntityComServerClusterServer>
  nameWithType: List<EntityComServerClusterServer>
  fullName: System.Collections.Generic.List<Toems_Common.Entity.EntityComServerClusterServer>
  nameWithType.vb: List(Of EntityComServerClusterServer)
  fullName.vb: System.Collections.Generic.List(Of Toems_Common.Entity.EntityComServerClusterServer)
  name.vb: List(Of EntityComServerClusterServer)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Toems_Common.Entity.EntityComServerClusterServer
    name: EntityComServerClusterServer
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Toems_Common.Entity.EntityComServerClusterServer
    name: EntityComServerClusterServer
    isExternal: true
  - name: )
- uid: Toems_Common.Dto.DtoActionResult
  isExternal: true
  name: DtoActionResult
  nameWithType: DtoActionResult
  fullName: Toems_Common.Dto.DtoActionResult
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
