### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.PolicyCategoryController
  commentId: T:Toems_ApplicationApi.Controllers.PolicyCategoryController
  id: PolicyCategoryController
  parent: Toems_ApplicationApi.Controllers
  children:
  - Toems_ApplicationApi.Controllers.PolicyCategoryController.#ctor
  - Toems_ApplicationApi.Controllers.PolicyCategoryController.Delete(System.Int32)
  - Toems_ApplicationApi.Controllers.PolicyCategoryController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityPolicyCategory})
  langs:
  - csharp
  - vb
  name: PolicyCategoryController
  nameWithType: PolicyCategoryController
  fullName: Toems_ApplicationApi.Controllers.PolicyCategoryController
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: 'public class PolicyCategoryController : ApiController'
    content.vb: Public Class PolicyCategoryController Inherits ApiController
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.Controllers.PolicyCategoryController.#ctor
  commentId: M:Toems_ApplicationApi.Controllers.PolicyCategoryController.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.Controllers.PolicyCategoryController
  langs:
  - csharp
  - vb
  name: PolicyCategoryController()
  nameWithType: PolicyCategoryController.PolicyCategoryController()
  fullName: Toems_ApplicationApi.Controllers.PolicyCategoryController.PolicyCategoryController()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public PolicyCategoryController()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.Controllers.PolicyCategoryController.#ctor*
  nameWithType.vb: PolicyCategoryController.New()
  fullName.vb: Toems_ApplicationApi.Controllers.PolicyCategoryController.New()
  name.vb: New()
- uid: Toems_ApplicationApi.Controllers.PolicyCategoryController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityPolicyCategory})
  commentId: M:Toems_ApplicationApi.Controllers.PolicyCategoryController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityPolicyCategory})
  id: Post(System.Collections.Generic.List{Toems_Common.Entity.EntityPolicyCategory})
  parent: Toems_ApplicationApi.Controllers.PolicyCategoryController
  langs:
  - csharp
  - vb
  name: Post(List<EntityPolicyCategory>)
  nameWithType: PolicyCategoryController.Post(List<EntityPolicyCategory>)
  fullName: Toems_ApplicationApi.Controllers.PolicyCategoryController.Post(System.Collections.Generic.List<Toems_Common.Entity.EntityPolicyCategory>)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "policyUpdate")]

      public DtoActionResult Post(List<EntityPolicyCategory> policyCategories)
    parameters:
    - id: policyCategories
      type: System.Collections.Generic.List{Toems_Common.Entity.EntityPolicyCategory}
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="policyUpdate")>

      Public Function Post(policyCategories As List(Of EntityPolicyCategory)) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.PolicyCategoryController.Post*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: policyUpdate
  nameWithType.vb: PolicyCategoryController.Post(List(Of EntityPolicyCategory))
  fullName.vb: Toems_ApplicationApi.Controllers.PolicyCategoryController.Post(System.Collections.Generic.List(Of Toems_Common.Entity.EntityPolicyCategory))
  name.vb: Post(List(Of EntityPolicyCategory))
- uid: Toems_ApplicationApi.Controllers.PolicyCategoryController.Delete(System.Int32)
  commentId: M:Toems_ApplicationApi.Controllers.PolicyCategoryController.Delete(System.Int32)
  id: Delete(System.Int32)
  parent: Toems_ApplicationApi.Controllers.PolicyCategoryController
  langs:
  - csharp
  - vb
  name: Delete(int)
  nameWithType: PolicyCategoryController.Delete(int)
  fullName: Toems_ApplicationApi.Controllers.PolicyCategoryController.Delete(int)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "policyUpdate")]

      public DtoActionResult Delete(int id)
    parameters:
    - id: id
      type: System.Int32
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="policyUpdate")>

      Public Function Delete(id As Integer) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.PolicyCategoryController.Delete*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: policyUpdate
  nameWithType.vb: PolicyCategoryController.Delete(Integer)
  fullName.vb: Toems_ApplicationApi.Controllers.PolicyCategoryController.Delete(Integer)
  name.vb: Delete(Integer)
references:
- uid: Toems_ApplicationApi.Controllers
  commentId: N:Toems_ApplicationApi.Controllers
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers
  nameWithType: Toems_ApplicationApi.Controllers
  fullName: Toems_ApplicationApi.Controllers
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.Controllers.PolicyCategoryController.#ctor*
  commentId: Overload:Toems_ApplicationApi.Controllers.PolicyCategoryController.#ctor
  isExternal: true
  href: Toems_ApplicationApi.Controllers.PolicyCategoryController.html#Toems_ApplicationApi.Controllers.PolicyCategoryController.#ctor
  name: PolicyCategoryController
  nameWithType: PolicyCategoryController.PolicyCategoryController
  fullName: Toems_ApplicationApi.Controllers.PolicyCategoryController.PolicyCategoryController
  nameWithType.vb: PolicyCategoryController.New
  fullName.vb: Toems_ApplicationApi.Controllers.PolicyCategoryController.New
  name.vb: New
- uid: Toems_ApplicationApi.Controllers.PolicyCategoryController.Post*
  commentId: Overload:Toems_ApplicationApi.Controllers.PolicyCategoryController.Post
  isExternal: true
  href: Toems_ApplicationApi.Controllers.PolicyCategoryController.html#Toems_ApplicationApi.Controllers.PolicyCategoryController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityPolicyCategory})
  name: Post
  nameWithType: PolicyCategoryController.Post
  fullName: Toems_ApplicationApi.Controllers.PolicyCategoryController.Post
- uid: System.Collections.Generic.List{Toems_Common.Entity.EntityPolicyCategory}
  commentId: T:System.Collections.Generic.List{Toems_Common.Entity.EntityPolicyCategory}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<EntityPolicyCategory>
  nameWithType: List<EntityPolicyCategory>
  fullName: System.Collections.Generic.List<Toems_Common.Entity.EntityPolicyCategory>
  nameWithType.vb: List(Of EntityPolicyCategory)
  fullName.vb: System.Collections.Generic.List(Of Toems_Common.Entity.EntityPolicyCategory)
  name.vb: List(Of EntityPolicyCategory)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Toems_Common.Entity.EntityPolicyCategory
    name: EntityPolicyCategory
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Toems_Common.Entity.EntityPolicyCategory
    name: EntityPolicyCategory
    isExternal: true
  - name: )
- uid: Toems_Common.Dto.DtoActionResult
  isExternal: true
  name: DtoActionResult
  nameWithType: DtoActionResult
  fullName: Toems_Common.Dto.DtoActionResult
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Toems_ApplicationApi.Controllers.PolicyCategoryController.Delete*
  commentId: Overload:Toems_ApplicationApi.Controllers.PolicyCategoryController.Delete
  isExternal: true
  href: Toems_ApplicationApi.Controllers.PolicyCategoryController.html#Toems_ApplicationApi.Controllers.PolicyCategoryController.Delete(System.Int32)
  name: Delete
  nameWithType: PolicyCategoryController.Delete
  fullName: Toems_ApplicationApi.Controllers.PolicyCategoryController.Delete
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
