### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.WieBuildController
  commentId: T:Toems_ApplicationApi.Controllers.WieBuildController
  id: WieBuildController
  parent: Toems_ApplicationApi.Controllers
  children:
  - Toems_ApplicationApi.Controllers.WieBuildController.#ctor
  - Toems_ApplicationApi.Controllers.WieBuildController.CheckIsoExists
  - Toems_ApplicationApi.Controllers.WieBuildController.ExportWie
  - Toems_ApplicationApi.Controllers.WieBuildController.GetLastBuild
  - Toems_ApplicationApi.Controllers.WieBuildController.GetProcess
  - Toems_ApplicationApi.Controllers.WieBuildController.UpdateStatus
  langs:
  - csharp
  - vb
  name: WieBuildController
  nameWithType: WieBuildController
  fullName: Toems_ApplicationApi.Controllers.WieBuildController
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: 'public class WieBuildController : ApiController'
    content.vb: Public Class WieBuildController Inherits ApiController
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.Controllers.WieBuildController.#ctor
  commentId: M:Toems_ApplicationApi.Controllers.WieBuildController.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.Controllers.WieBuildController
  langs:
  - csharp
  - vb
  name: WieBuildController()
  nameWithType: WieBuildController.WieBuildController()
  fullName: Toems_ApplicationApi.Controllers.WieBuildController.WieBuildController()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public WieBuildController()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.Controllers.WieBuildController.#ctor*
  nameWithType.vb: WieBuildController.New()
  fullName.vb: Toems_ApplicationApi.Controllers.WieBuildController.New()
  name.vb: New()
- uid: Toems_ApplicationApi.Controllers.WieBuildController.GetLastBuild
  commentId: M:Toems_ApplicationApi.Controllers.WieBuildController.GetLastBuild
  id: GetLastBuild
  parent: Toems_ApplicationApi.Controllers.WieBuildController
  langs:
  - csharp
  - vb
  name: GetLastBuild()
  nameWithType: WieBuildController.GetLastBuild()
  fullName: Toems_ApplicationApi.Controllers.WieBuildController.GetLastBuild()
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "Administrator")]

      public EntityWieBuild GetLastBuild()
    return:
      type: Toems_Common.Entity.EntityWieBuild
    content.vb: >-
      <CustomAuth(Permission:="Administrator")>

      Public Function GetLastBuild() As EntityWieBuild
  overload: Toems_ApplicationApi.Controllers.WieBuildController.GetLastBuild*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: Administrator
- uid: Toems_ApplicationApi.Controllers.WieBuildController.UpdateStatus
  commentId: M:Toems_ApplicationApi.Controllers.WieBuildController.UpdateStatus
  id: UpdateStatus
  parent: Toems_ApplicationApi.Controllers.WieBuildController
  langs:
  - csharp
  - vb
  name: UpdateStatus()
  nameWithType: WieBuildController.UpdateStatus()
  fullName: Toems_ApplicationApi.Controllers.WieBuildController.UpdateStatus()
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "Administrator")]

      public DtoApiBoolResponse UpdateStatus()
    return:
      type: Toems_Common.Dto.DtoApiBoolResponse
    content.vb: >-
      <CustomAuth(Permission:="Administrator")>

      Public Function UpdateStatus() As DtoApiBoolResponse
  overload: Toems_ApplicationApi.Controllers.WieBuildController.UpdateStatus*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: Administrator
- uid: Toems_ApplicationApi.Controllers.WieBuildController.GetProcess
  commentId: M:Toems_ApplicationApi.Controllers.WieBuildController.GetProcess
  id: GetProcess
  parent: Toems_ApplicationApi.Controllers.WieBuildController
  langs:
  - csharp
  - vb
  name: GetProcess()
  nameWithType: WieBuildController.GetProcess()
  fullName: Toems_ApplicationApi.Controllers.WieBuildController.GetProcess()
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "Administrator")]

      public List<DtoReplicationProcess> GetProcess()
    return:
      type: System.Collections.Generic.List{Toems_Common.Dto.DtoReplicationProcess}
    content.vb: >-
      <CustomAuth(Permission:="Administrator")>

      Public Function GetProcess() As List(Of DtoReplicationProcess)
  overload: Toems_ApplicationApi.Controllers.WieBuildController.GetProcess*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: Administrator
- uid: Toems_ApplicationApi.Controllers.WieBuildController.ExportWie
  commentId: M:Toems_ApplicationApi.Controllers.WieBuildController.ExportWie
  id: ExportWie
  parent: Toems_ApplicationApi.Controllers.WieBuildController
  langs:
  - csharp
  - vb
  name: ExportWie()
  nameWithType: WieBuildController.ExportWie()
  fullName: Toems_ApplicationApi.Controllers.WieBuildController.ExportWie()
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "Administrator")]

      public HttpResponseMessage ExportWie()
    return:
      type: System.Net.Http.HttpResponseMessage
    content.vb: >-
      <CustomAuth(Permission:="Administrator")>

      Public Function ExportWie() As HttpResponseMessage
  overload: Toems_ApplicationApi.Controllers.WieBuildController.ExportWie*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: Administrator
- uid: Toems_ApplicationApi.Controllers.WieBuildController.CheckIsoExists
  commentId: M:Toems_ApplicationApi.Controllers.WieBuildController.CheckIsoExists
  id: CheckIsoExists
  parent: Toems_ApplicationApi.Controllers.WieBuildController
  langs:
  - csharp
  - vb
  name: CheckIsoExists()
  nameWithType: WieBuildController.CheckIsoExists()
  fullName: Toems_ApplicationApi.Controllers.WieBuildController.CheckIsoExists()
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "Administrator")]

      public DtoApiBoolResponse CheckIsoExists()
    return:
      type: Toems_Common.Dto.DtoApiBoolResponse
    content.vb: >-
      <CustomAuth(Permission:="Administrator")>

      Public Function CheckIsoExists() As DtoApiBoolResponse
  overload: Toems_ApplicationApi.Controllers.WieBuildController.CheckIsoExists*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: Administrator
references:
- uid: Toems_ApplicationApi.Controllers
  commentId: N:Toems_ApplicationApi.Controllers
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers
  nameWithType: Toems_ApplicationApi.Controllers
  fullName: Toems_ApplicationApi.Controllers
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.Controllers.WieBuildController.#ctor*
  commentId: Overload:Toems_ApplicationApi.Controllers.WieBuildController.#ctor
  isExternal: true
  href: Toems_ApplicationApi.Controllers.WieBuildController.html#Toems_ApplicationApi.Controllers.WieBuildController.#ctor
  name: WieBuildController
  nameWithType: WieBuildController.WieBuildController
  fullName: Toems_ApplicationApi.Controllers.WieBuildController.WieBuildController
  nameWithType.vb: WieBuildController.New
  fullName.vb: Toems_ApplicationApi.Controllers.WieBuildController.New
  name.vb: New
- uid: Toems_ApplicationApi.Controllers.WieBuildController.GetLastBuild*
  commentId: Overload:Toems_ApplicationApi.Controllers.WieBuildController.GetLastBuild
  isExternal: true
  href: Toems_ApplicationApi.Controllers.WieBuildController.html#Toems_ApplicationApi.Controllers.WieBuildController.GetLastBuild
  name: GetLastBuild
  nameWithType: WieBuildController.GetLastBuild
  fullName: Toems_ApplicationApi.Controllers.WieBuildController.GetLastBuild
- uid: Toems_Common.Entity.EntityWieBuild
  commentId: '!:Toems_Common.Entity.EntityWieBuild'
  isExternal: true
  name: EntityWieBuild
  nameWithType: EntityWieBuild
  fullName: Toems_Common.Entity.EntityWieBuild
- uid: Toems_ApplicationApi.Controllers.WieBuildController.UpdateStatus*
  commentId: Overload:Toems_ApplicationApi.Controllers.WieBuildController.UpdateStatus
  isExternal: true
  href: Toems_ApplicationApi.Controllers.WieBuildController.html#Toems_ApplicationApi.Controllers.WieBuildController.UpdateStatus
  name: UpdateStatus
  nameWithType: WieBuildController.UpdateStatus
  fullName: Toems_ApplicationApi.Controllers.WieBuildController.UpdateStatus
- uid: Toems_Common.Dto.DtoApiBoolResponse
  isExternal: true
  name: DtoApiBoolResponse
  nameWithType: DtoApiBoolResponse
  fullName: Toems_Common.Dto.DtoApiBoolResponse
- uid: Toems_ApplicationApi.Controllers.WieBuildController.GetProcess*
  commentId: Overload:Toems_ApplicationApi.Controllers.WieBuildController.GetProcess
  isExternal: true
  href: Toems_ApplicationApi.Controllers.WieBuildController.html#Toems_ApplicationApi.Controllers.WieBuildController.GetProcess
  name: GetProcess
  nameWithType: WieBuildController.GetProcess
  fullName: Toems_ApplicationApi.Controllers.WieBuildController.GetProcess
- uid: System.Collections.Generic.List{Toems_Common.Dto.DtoReplicationProcess}
  commentId: T:System.Collections.Generic.List{Toems_Common.Dto.DtoReplicationProcess}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<DtoReplicationProcess>
  nameWithType: List<DtoReplicationProcess>
  fullName: System.Collections.Generic.List<Toems_Common.Dto.DtoReplicationProcess>
  nameWithType.vb: List(Of DtoReplicationProcess)
  fullName.vb: System.Collections.Generic.List(Of Toems_Common.Dto.DtoReplicationProcess)
  name.vb: List(Of DtoReplicationProcess)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Toems_Common.Dto.DtoReplicationProcess
    name: DtoReplicationProcess
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Toems_Common.Dto.DtoReplicationProcess
    name: DtoReplicationProcess
    isExternal: true
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Toems_ApplicationApi.Controllers.WieBuildController.ExportWie*
  commentId: Overload:Toems_ApplicationApi.Controllers.WieBuildController.ExportWie
  isExternal: true
  href: Toems_ApplicationApi.Controllers.WieBuildController.html#Toems_ApplicationApi.Controllers.WieBuildController.ExportWie
  name: ExportWie
  nameWithType: WieBuildController.ExportWie
  fullName: Toems_ApplicationApi.Controllers.WieBuildController.ExportWie
- uid: System.Net.Http.HttpResponseMessage
  isExternal: true
  name: HttpResponseMessage
  nameWithType: HttpResponseMessage
  fullName: System.Net.Http.HttpResponseMessage
- uid: Toems_ApplicationApi.Controllers.WieBuildController.CheckIsoExists*
  commentId: Overload:Toems_ApplicationApi.Controllers.WieBuildController.CheckIsoExists
  isExternal: true
  href: Toems_ApplicationApi.Controllers.WieBuildController.html#Toems_ApplicationApi.Controllers.WieBuildController.CheckIsoExists
  name: CheckIsoExists
  nameWithType: WieBuildController.CheckIsoExists
  fullName: Toems_ApplicationApi.Controllers.WieBuildController.CheckIsoExists
