### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.UserGroupRightController
  commentId: T:Toems_ApplicationApi.Controllers.UserGroupRightController
  id: UserGroupRightController
  parent: Toems_ApplicationApi.Controllers
  children:
  - Toems_ApplicationApi.Controllers.UserGroupRightController.#ctor
  - Toems_ApplicationApi.Controllers.UserGroupRightController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityUserGroupRight})
  langs:
  - csharp
  - vb
  name: UserGroupRightController
  nameWithType: UserGroupRightController
  fullName: Toems_ApplicationApi.Controllers.UserGroupRightController
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: 'public class UserGroupRightController : ApiController'
    content.vb: Public Class UserGroupRightController Inherits ApiController
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.Controllers.UserGroupRightController.#ctor
  commentId: M:Toems_ApplicationApi.Controllers.UserGroupRightController.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.Controllers.UserGroupRightController
  langs:
  - csharp
  - vb
  name: UserGroupRightController()
  nameWithType: UserGroupRightController.UserGroupRightController()
  fullName: Toems_ApplicationApi.Controllers.UserGroupRightController.UserGroupRightController()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public UserGroupRightController()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.Controllers.UserGroupRightController.#ctor*
  nameWithType.vb: UserGroupRightController.New()
  fullName.vb: Toems_ApplicationApi.Controllers.UserGroupRightController.New()
  name.vb: New()
- uid: Toems_ApplicationApi.Controllers.UserGroupRightController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityUserGroupRight})
  commentId: M:Toems_ApplicationApi.Controllers.UserGroupRightController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityUserGroupRight})
  id: Post(System.Collections.Generic.List{Toems_Common.Entity.EntityUserGroupRight})
  parent: Toems_ApplicationApi.Controllers.UserGroupRightController
  langs:
  - csharp
  - vb
  name: Post(List<EntityUserGroupRight>)
  nameWithType: UserGroupRightController.Post(List<EntityUserGroupRight>)
  fullName: Toems_ApplicationApi.Controllers.UserGroupRightController.Post(System.Collections.Generic.List<Toems_Common.Entity.EntityUserGroupRight>)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "Administrator")]

      public DtoActionResult Post(List<EntityUserGroupRight> listOfRights)
    parameters:
    - id: listOfRights
      type: System.Collections.Generic.List{Toems_Common.Entity.EntityUserGroupRight}
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="Administrator")>

      Public Function Post(listOfRights As List(Of EntityUserGroupRight)) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.UserGroupRightController.Post*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: Administrator
  nameWithType.vb: UserGroupRightController.Post(List(Of EntityUserGroupRight))
  fullName.vb: Toems_ApplicationApi.Controllers.UserGroupRightController.Post(System.Collections.Generic.List(Of Toems_Common.Entity.EntityUserGroupRight))
  name.vb: Post(List(Of EntityUserGroupRight))
references:
- uid: Toems_ApplicationApi.Controllers
  commentId: N:Toems_ApplicationApi.Controllers
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers
  nameWithType: Toems_ApplicationApi.Controllers
  fullName: Toems_ApplicationApi.Controllers
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.Controllers.UserGroupRightController.#ctor*
  commentId: Overload:Toems_ApplicationApi.Controllers.UserGroupRightController.#ctor
  isExternal: true
  href: Toems_ApplicationApi.Controllers.UserGroupRightController.html#Toems_ApplicationApi.Controllers.UserGroupRightController.#ctor
  name: UserGroupRightController
  nameWithType: UserGroupRightController.UserGroupRightController
  fullName: Toems_ApplicationApi.Controllers.UserGroupRightController.UserGroupRightController
  nameWithType.vb: UserGroupRightController.New
  fullName.vb: Toems_ApplicationApi.Controllers.UserGroupRightController.New
  name.vb: New
- uid: Toems_ApplicationApi.Controllers.UserGroupRightController.Post*
  commentId: Overload:Toems_ApplicationApi.Controllers.UserGroupRightController.Post
  isExternal: true
  href: Toems_ApplicationApi.Controllers.UserGroupRightController.html#Toems_ApplicationApi.Controllers.UserGroupRightController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityUserGroupRight})
  name: Post
  nameWithType: UserGroupRightController.Post
  fullName: Toems_ApplicationApi.Controllers.UserGroupRightController.Post
- uid: System.Collections.Generic.List{Toems_Common.Entity.EntityUserGroupRight}
  commentId: T:System.Collections.Generic.List{Toems_Common.Entity.EntityUserGroupRight}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<EntityUserGroupRight>
  nameWithType: List<EntityUserGroupRight>
  fullName: System.Collections.Generic.List<Toems_Common.Entity.EntityUserGroupRight>
  nameWithType.vb: List(Of EntityUserGroupRight)
  fullName.vb: System.Collections.Generic.List(Of Toems_Common.Entity.EntityUserGroupRight)
  name.vb: List(Of EntityUserGroupRight)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Toems_Common.Entity.EntityUserGroupRight
    name: EntityUserGroupRight
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Toems_Common.Entity.EntityUserGroupRight
    name: EntityUserGroupRight
    isExternal: true
  - name: )
- uid: Toems_Common.Dto.DtoActionResult
  isExternal: true
  name: DtoActionResult
  nameWithType: DtoActionResult
  fullName: Toems_Common.Dto.DtoActionResult
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
