### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.UserRightController
  commentId: T:Toems_ApplicationApi.Controllers.UserRightController
  id: UserRightController
  parent: Toems_ApplicationApi.Controllers
  children:
  - Toems_ApplicationApi.Controllers.UserRightController.#ctor
  - Toems_ApplicationApi.Controllers.UserRightController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityUserRight})
  langs:
  - csharp
  - vb
  name: UserRightController
  nameWithType: UserRightController
  fullName: Toems_ApplicationApi.Controllers.UserRightController
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: 'public class UserRightController : ApiController'
    content.vb: Public Class UserRightController Inherits ApiController
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.Controllers.UserRightController.#ctor
  commentId: M:Toems_ApplicationApi.Controllers.UserRightController.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.Controllers.UserRightController
  langs:
  - csharp
  - vb
  name: UserRightController()
  nameWithType: UserRightController.UserRightController()
  fullName: Toems_ApplicationApi.Controllers.UserRightController.UserRightController()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public UserRightController()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.Controllers.UserRightController.#ctor*
  nameWithType.vb: UserRightController.New()
  fullName.vb: Toems_ApplicationApi.Controllers.UserRightController.New()
  name.vb: New()
- uid: Toems_ApplicationApi.Controllers.UserRightController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityUserRight})
  commentId: M:Toems_ApplicationApi.Controllers.UserRightController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityUserRight})
  id: Post(System.Collections.Generic.List{Toems_Common.Entity.EntityUserRight})
  parent: Toems_ApplicationApi.Controllers.UserRightController
  langs:
  - csharp
  - vb
  name: Post(List<EntityUserRight>)
  nameWithType: UserRightController.Post(List<EntityUserRight>)
  fullName: Toems_ApplicationApi.Controllers.UserRightController.Post(System.Collections.Generic.List<Toems_Common.Entity.EntityUserRight>)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "Administrator")]

      public DtoActionResult Post(List<EntityUserRight> listOfRights)
    parameters:
    - id: listOfRights
      type: System.Collections.Generic.List{Toems_Common.Entity.EntityUserRight}
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="Administrator")>

      Public Function Post(listOfRights As List(Of EntityUserRight)) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.UserRightController.Post*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: Administrator
  nameWithType.vb: UserRightController.Post(List(Of EntityUserRight))
  fullName.vb: Toems_ApplicationApi.Controllers.UserRightController.Post(System.Collections.Generic.List(Of Toems_Common.Entity.EntityUserRight))
  name.vb: Post(List(Of EntityUserRight))
references:
- uid: Toems_ApplicationApi.Controllers
  commentId: N:Toems_ApplicationApi.Controllers
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers
  nameWithType: Toems_ApplicationApi.Controllers
  fullName: Toems_ApplicationApi.Controllers
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.Controllers.UserRightController.#ctor*
  commentId: Overload:Toems_ApplicationApi.Controllers.UserRightController.#ctor
  isExternal: true
  href: Toems_ApplicationApi.Controllers.UserRightController.html#Toems_ApplicationApi.Controllers.UserRightController.#ctor
  name: UserRightController
  nameWithType: UserRightController.UserRightController
  fullName: Toems_ApplicationApi.Controllers.UserRightController.UserRightController
  nameWithType.vb: UserRightController.New
  fullName.vb: Toems_ApplicationApi.Controllers.UserRightController.New
  name.vb: New
- uid: Toems_ApplicationApi.Controllers.UserRightController.Post*
  commentId: Overload:Toems_ApplicationApi.Controllers.UserRightController.Post
  isExternal: true
  href: Toems_ApplicationApi.Controllers.UserRightController.html#Toems_ApplicationApi.Controllers.UserRightController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityUserRight})
  name: Post
  nameWithType: UserRightController.Post
  fullName: Toems_ApplicationApi.Controllers.UserRightController.Post
- uid: System.Collections.Generic.List{Toems_Common.Entity.EntityUserRight}
  commentId: T:System.Collections.Generic.List{Toems_Common.Entity.EntityUserRight}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<EntityUserRight>
  nameWithType: List<EntityUserRight>
  fullName: System.Collections.Generic.List<Toems_Common.Entity.EntityUserRight>
  nameWithType.vb: List(Of EntityUserRight)
  fullName.vb: System.Collections.Generic.List(Of Toems_Common.Entity.EntityUserRight)
  name.vb: List(Of EntityUserRight)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Toems_Common.Entity.EntityUserRight
    name: EntityUserRight
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Toems_Common.Entity.EntityUserRight
    name: EntityUserRight
    isExternal: true
  - name: )
- uid: Toems_Common.Dto.DtoActionResult
  isExternal: true
  name: DtoActionResult
  nameWithType: DtoActionResult
  fullName: Toems_Common.Dto.DtoActionResult
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
