### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.ImageCategoryController
  commentId: T:Toems_ApplicationApi.Controllers.ImageCategoryController
  id: ImageCategoryController
  parent: Toems_ApplicationApi.Controllers
  children:
  - Toems_ApplicationApi.Controllers.ImageCategoryController.#ctor
  - Toems_ApplicationApi.Controllers.ImageCategoryController.Delete(System.Int32)
  - Toems_ApplicationApi.Controllers.ImageCategoryController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityImageCategory})
  langs:
  - csharp
  - vb
  name: ImageCategoryController
  nameWithType: ImageCategoryController
  fullName: Toems_ApplicationApi.Controllers.ImageCategoryController
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: 'public class ImageCategoryController : ApiController'
    content.vb: Public Class ImageCategoryController Inherits ApiController
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.Controllers.ImageCategoryController.#ctor
  commentId: M:Toems_ApplicationApi.Controllers.ImageCategoryController.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.Controllers.ImageCategoryController
  langs:
  - csharp
  - vb
  name: ImageCategoryController()
  nameWithType: ImageCategoryController.ImageCategoryController()
  fullName: Toems_ApplicationApi.Controllers.ImageCategoryController.ImageCategoryController()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public ImageCategoryController()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.Controllers.ImageCategoryController.#ctor*
  nameWithType.vb: ImageCategoryController.New()
  fullName.vb: Toems_ApplicationApi.Controllers.ImageCategoryController.New()
  name.vb: New()
- uid: Toems_ApplicationApi.Controllers.ImageCategoryController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityImageCategory})
  commentId: M:Toems_ApplicationApi.Controllers.ImageCategoryController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityImageCategory})
  id: Post(System.Collections.Generic.List{Toems_Common.Entity.EntityImageCategory})
  parent: Toems_ApplicationApi.Controllers.ImageCategoryController
  langs:
  - csharp
  - vb
  name: Post(List<EntityImageCategory>)
  nameWithType: ImageCategoryController.Post(List<EntityImageCategory>)
  fullName: Toems_ApplicationApi.Controllers.ImageCategoryController.Post(System.Collections.Generic.List<Toems_Common.Entity.EntityImageCategory>)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "imageUpdate")]

      public DtoActionResult Post(List<EntityImageCategory> imageCategories)
    parameters:
    - id: imageCategories
      type: System.Collections.Generic.List{Toems_Common.Entity.EntityImageCategory}
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="imageUpdate")>

      Public Function Post(imageCategories As List(Of EntityImageCategory)) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.ImageCategoryController.Post*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: imageUpdate
  nameWithType.vb: ImageCategoryController.Post(List(Of EntityImageCategory))
  fullName.vb: Toems_ApplicationApi.Controllers.ImageCategoryController.Post(System.Collections.Generic.List(Of Toems_Common.Entity.EntityImageCategory))
  name.vb: Post(List(Of EntityImageCategory))
- uid: Toems_ApplicationApi.Controllers.ImageCategoryController.Delete(System.Int32)
  commentId: M:Toems_ApplicationApi.Controllers.ImageCategoryController.Delete(System.Int32)
  id: Delete(System.Int32)
  parent: Toems_ApplicationApi.Controllers.ImageCategoryController
  langs:
  - csharp
  - vb
  name: Delete(int)
  nameWithType: ImageCategoryController.Delete(int)
  fullName: Toems_ApplicationApi.Controllers.ImageCategoryController.Delete(int)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "imageUpdate")]

      public DtoActionResult Delete(int id)
    parameters:
    - id: id
      type: System.Int32
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="imageUpdate")>

      Public Function Delete(id As Integer) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.ImageCategoryController.Delete*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: imageUpdate
  nameWithType.vb: ImageCategoryController.Delete(Integer)
  fullName.vb: Toems_ApplicationApi.Controllers.ImageCategoryController.Delete(Integer)
  name.vb: Delete(Integer)
references:
- uid: Toems_ApplicationApi.Controllers
  commentId: N:Toems_ApplicationApi.Controllers
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers
  nameWithType: Toems_ApplicationApi.Controllers
  fullName: Toems_ApplicationApi.Controllers
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.Controllers.ImageCategoryController.#ctor*
  commentId: Overload:Toems_ApplicationApi.Controllers.ImageCategoryController.#ctor
  isExternal: true
  href: Toems_ApplicationApi.Controllers.ImageCategoryController.html#Toems_ApplicationApi.Controllers.ImageCategoryController.#ctor
  name: ImageCategoryController
  nameWithType: ImageCategoryController.ImageCategoryController
  fullName: Toems_ApplicationApi.Controllers.ImageCategoryController.ImageCategoryController
  nameWithType.vb: ImageCategoryController.New
  fullName.vb: Toems_ApplicationApi.Controllers.ImageCategoryController.New
  name.vb: New
- uid: Toems_ApplicationApi.Controllers.ImageCategoryController.Post*
  commentId: Overload:Toems_ApplicationApi.Controllers.ImageCategoryController.Post
  isExternal: true
  href: Toems_ApplicationApi.Controllers.ImageCategoryController.html#Toems_ApplicationApi.Controllers.ImageCategoryController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityImageCategory})
  name: Post
  nameWithType: ImageCategoryController.Post
  fullName: Toems_ApplicationApi.Controllers.ImageCategoryController.Post
- uid: System.Collections.Generic.List{Toems_Common.Entity.EntityImageCategory}
  commentId: T:System.Collections.Generic.List{Toems_Common.Entity.EntityImageCategory}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<EntityImageCategory>
  nameWithType: List<EntityImageCategory>
  fullName: System.Collections.Generic.List<Toems_Common.Entity.EntityImageCategory>
  nameWithType.vb: List(Of EntityImageCategory)
  fullName.vb: System.Collections.Generic.List(Of Toems_Common.Entity.EntityImageCategory)
  name.vb: List(Of EntityImageCategory)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Toems_Common.Entity.EntityImageCategory
    name: EntityImageCategory
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Toems_Common.Entity.EntityImageCategory
    name: EntityImageCategory
    isExternal: true
  - name: )
- uid: Toems_Common.Dto.DtoActionResult
  isExternal: true
  name: DtoActionResult
  nameWithType: DtoActionResult
  fullName: Toems_Common.Dto.DtoActionResult
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Toems_ApplicationApi.Controllers.ImageCategoryController.Delete*
  commentId: Overload:Toems_ApplicationApi.Controllers.ImageCategoryController.Delete
  isExternal: true
  href: Toems_ApplicationApi.Controllers.ImageCategoryController.html#Toems_ApplicationApi.Controllers.ImageCategoryController.Delete(System.Int32)
  name: Delete
  nameWithType: ImageCategoryController.Delete
  fullName: Toems_ApplicationApi.Controllers.ImageCategoryController.Delete
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
