### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.GroupCategoryController
  commentId: T:Toems_ApplicationApi.Controllers.GroupCategoryController
  id: GroupCategoryController
  parent: Toems_ApplicationApi.Controllers
  children:
  - Toems_ApplicationApi.Controllers.GroupCategoryController.#ctor
  - Toems_ApplicationApi.Controllers.GroupCategoryController.Delete(System.Int32)
  - Toems_ApplicationApi.Controllers.GroupCategoryController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityGroupCategory})
  langs:
  - csharp
  - vb
  name: GroupCategoryController
  nameWithType: GroupCategoryController
  fullName: Toems_ApplicationApi.Controllers.GroupCategoryController
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: 'public class GroupCategoryController : ApiController'
    content.vb: Public Class GroupCategoryController Inherits ApiController
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.Controllers.GroupCategoryController.#ctor
  commentId: M:Toems_ApplicationApi.Controllers.GroupCategoryController.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.Controllers.GroupCategoryController
  langs:
  - csharp
  - vb
  name: GroupCategoryController()
  nameWithType: GroupCategoryController.GroupCategoryController()
  fullName: Toems_ApplicationApi.Controllers.GroupCategoryController.GroupCategoryController()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public GroupCategoryController()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.Controllers.GroupCategoryController.#ctor*
  nameWithType.vb: GroupCategoryController.New()
  fullName.vb: Toems_ApplicationApi.Controllers.GroupCategoryController.New()
  name.vb: New()
- uid: Toems_ApplicationApi.Controllers.GroupCategoryController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityGroupCategory})
  commentId: M:Toems_ApplicationApi.Controllers.GroupCategoryController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityGroupCategory})
  id: Post(System.Collections.Generic.List{Toems_Common.Entity.EntityGroupCategory})
  parent: Toems_ApplicationApi.Controllers.GroupCategoryController
  langs:
  - csharp
  - vb
  name: Post(List<EntityGroupCategory>)
  nameWithType: GroupCategoryController.Post(List<EntityGroupCategory>)
  fullName: Toems_ApplicationApi.Controllers.GroupCategoryController.Post(System.Collections.Generic.List<Toems_Common.Entity.EntityGroupCategory>)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "groupUpdate")]

      public DtoActionResult Post(List<EntityGroupCategory> groupCategories)
    parameters:
    - id: groupCategories
      type: System.Collections.Generic.List{Toems_Common.Entity.EntityGroupCategory}
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="groupUpdate")>

      Public Function Post(groupCategories As List(Of EntityGroupCategory)) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.GroupCategoryController.Post*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: groupUpdate
  nameWithType.vb: GroupCategoryController.Post(List(Of EntityGroupCategory))
  fullName.vb: Toems_ApplicationApi.Controllers.GroupCategoryController.Post(System.Collections.Generic.List(Of Toems_Common.Entity.EntityGroupCategory))
  name.vb: Post(List(Of EntityGroupCategory))
- uid: Toems_ApplicationApi.Controllers.GroupCategoryController.Delete(System.Int32)
  commentId: M:Toems_ApplicationApi.Controllers.GroupCategoryController.Delete(System.Int32)
  id: Delete(System.Int32)
  parent: Toems_ApplicationApi.Controllers.GroupCategoryController
  langs:
  - csharp
  - vb
  name: Delete(int)
  nameWithType: GroupCategoryController.Delete(int)
  fullName: Toems_ApplicationApi.Controllers.GroupCategoryController.Delete(int)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "groupDelete")]

      public DtoActionResult Delete(int id)
    parameters:
    - id: id
      type: System.Int32
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="groupDelete")>

      Public Function Delete(id As Integer) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.GroupCategoryController.Delete*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: groupDelete
  nameWithType.vb: GroupCategoryController.Delete(Integer)
  fullName.vb: Toems_ApplicationApi.Controllers.GroupCategoryController.Delete(Integer)
  name.vb: Delete(Integer)
references:
- uid: Toems_ApplicationApi.Controllers
  commentId: N:Toems_ApplicationApi.Controllers
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers
  nameWithType: Toems_ApplicationApi.Controllers
  fullName: Toems_ApplicationApi.Controllers
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.Controllers.GroupCategoryController.#ctor*
  commentId: Overload:Toems_ApplicationApi.Controllers.GroupCategoryController.#ctor
  isExternal: true
  href: Toems_ApplicationApi.Controllers.GroupCategoryController.html#Toems_ApplicationApi.Controllers.GroupCategoryController.#ctor
  name: GroupCategoryController
  nameWithType: GroupCategoryController.GroupCategoryController
  fullName: Toems_ApplicationApi.Controllers.GroupCategoryController.GroupCategoryController
  nameWithType.vb: GroupCategoryController.New
  fullName.vb: Toems_ApplicationApi.Controllers.GroupCategoryController.New
  name.vb: New
- uid: Toems_ApplicationApi.Controllers.GroupCategoryController.Post*
  commentId: Overload:Toems_ApplicationApi.Controllers.GroupCategoryController.Post
  isExternal: true
  href: Toems_ApplicationApi.Controllers.GroupCategoryController.html#Toems_ApplicationApi.Controllers.GroupCategoryController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityGroupCategory})
  name: Post
  nameWithType: GroupCategoryController.Post
  fullName: Toems_ApplicationApi.Controllers.GroupCategoryController.Post
- uid: System.Collections.Generic.List{Toems_Common.Entity.EntityGroupCategory}
  commentId: T:System.Collections.Generic.List{Toems_Common.Entity.EntityGroupCategory}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<EntityGroupCategory>
  nameWithType: List<EntityGroupCategory>
  fullName: System.Collections.Generic.List<Toems_Common.Entity.EntityGroupCategory>
  nameWithType.vb: List(Of EntityGroupCategory)
  fullName.vb: System.Collections.Generic.List(Of Toems_Common.Entity.EntityGroupCategory)
  name.vb: List(Of EntityGroupCategory)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Toems_Common.Entity.EntityGroupCategory
    name: EntityGroupCategory
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Toems_Common.Entity.EntityGroupCategory
    name: EntityGroupCategory
    isExternal: true
  - name: )
- uid: Toems_Common.Dto.DtoActionResult
  isExternal: true
  name: DtoActionResult
  nameWithType: DtoActionResult
  fullName: Toems_Common.Dto.DtoActionResult
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Toems_ApplicationApi.Controllers.GroupCategoryController.Delete*
  commentId: Overload:Toems_ApplicationApi.Controllers.GroupCategoryController.Delete
  isExternal: true
  href: Toems_ApplicationApi.Controllers.GroupCategoryController.html#Toems_ApplicationApi.Controllers.GroupCategoryController.Delete(System.Int32)
  name: Delete
  nameWithType: GroupCategoryController.Delete
  fullName: Toems_ApplicationApi.Controllers.GroupCategoryController.Delete
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
