### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.PolicyComServerController
  commentId: T:Toems_ApplicationApi.Controllers.PolicyComServerController
  id: PolicyComServerController
  parent: Toems_ApplicationApi.Controllers
  children:
  - Toems_ApplicationApi.Controllers.PolicyComServerController.#ctor
  - Toems_ApplicationApi.Controllers.PolicyComServerController.Delete(System.Int32)
  - Toems_ApplicationApi.Controllers.PolicyComServerController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityPolicyComServer})
  langs:
  - csharp
  - vb
  name: PolicyComServerController
  nameWithType: PolicyComServerController
  fullName: Toems_ApplicationApi.Controllers.PolicyComServerController
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: 'public class PolicyComServerController : ApiController'
    content.vb: Public Class PolicyComServerController Inherits ApiController
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.Controllers.PolicyComServerController.#ctor
  commentId: M:Toems_ApplicationApi.Controllers.PolicyComServerController.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.Controllers.PolicyComServerController
  langs:
  - csharp
  - vb
  name: PolicyComServerController()
  nameWithType: PolicyComServerController.PolicyComServerController()
  fullName: Toems_ApplicationApi.Controllers.PolicyComServerController.PolicyComServerController()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public PolicyComServerController()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.Controllers.PolicyComServerController.#ctor*
  nameWithType.vb: PolicyComServerController.New()
  fullName.vb: Toems_ApplicationApi.Controllers.PolicyComServerController.New()
  name.vb: New()
- uid: Toems_ApplicationApi.Controllers.PolicyComServerController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityPolicyComServer})
  commentId: M:Toems_ApplicationApi.Controllers.PolicyComServerController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityPolicyComServer})
  id: Post(System.Collections.Generic.List{Toems_Common.Entity.EntityPolicyComServer})
  parent: Toems_ApplicationApi.Controllers.PolicyComServerController
  langs:
  - csharp
  - vb
  name: Post(List<EntityPolicyComServer>)
  nameWithType: PolicyComServerController.Post(List<EntityPolicyComServer>)
  fullName: Toems_ApplicationApi.Controllers.PolicyComServerController.Post(System.Collections.Generic.List<Toems_Common.Entity.EntityPolicyComServer>)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "policyUpdate")]

      public DtoActionResult Post(List<EntityPolicyComServer> policyComServers)
    parameters:
    - id: policyComServers
      type: System.Collections.Generic.List{Toems_Common.Entity.EntityPolicyComServer}
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="policyUpdate")>

      Public Function Post(policyComServers As List(Of EntityPolicyComServer)) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.PolicyComServerController.Post*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: policyUpdate
  nameWithType.vb: PolicyComServerController.Post(List(Of EntityPolicyComServer))
  fullName.vb: Toems_ApplicationApi.Controllers.PolicyComServerController.Post(System.Collections.Generic.List(Of Toems_Common.Entity.EntityPolicyComServer))
  name.vb: Post(List(Of EntityPolicyComServer))
- uid: Toems_ApplicationApi.Controllers.PolicyComServerController.Delete(System.Int32)
  commentId: M:Toems_ApplicationApi.Controllers.PolicyComServerController.Delete(System.Int32)
  id: Delete(System.Int32)
  parent: Toems_ApplicationApi.Controllers.PolicyComServerController
  langs:
  - csharp
  - vb
  name: Delete(int)
  nameWithType: PolicyComServerController.Delete(int)
  fullName: Toems_ApplicationApi.Controllers.PolicyComServerController.Delete(int)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "policyUpdate")]

      public DtoActionResult Delete(int id)
    parameters:
    - id: id
      type: System.Int32
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="policyUpdate")>

      Public Function Delete(id As Integer) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.PolicyComServerController.Delete*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: policyUpdate
  nameWithType.vb: PolicyComServerController.Delete(Integer)
  fullName.vb: Toems_ApplicationApi.Controllers.PolicyComServerController.Delete(Integer)
  name.vb: Delete(Integer)
references:
- uid: Toems_ApplicationApi.Controllers
  commentId: N:Toems_ApplicationApi.Controllers
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers
  nameWithType: Toems_ApplicationApi.Controllers
  fullName: Toems_ApplicationApi.Controllers
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.Controllers.PolicyComServerController.#ctor*
  commentId: Overload:Toems_ApplicationApi.Controllers.PolicyComServerController.#ctor
  isExternal: true
  href: Toems_ApplicationApi.Controllers.PolicyComServerController.html#Toems_ApplicationApi.Controllers.PolicyComServerController.#ctor
  name: PolicyComServerController
  nameWithType: PolicyComServerController.PolicyComServerController
  fullName: Toems_ApplicationApi.Controllers.PolicyComServerController.PolicyComServerController
  nameWithType.vb: PolicyComServerController.New
  fullName.vb: Toems_ApplicationApi.Controllers.PolicyComServerController.New
  name.vb: New
- uid: Toems_ApplicationApi.Controllers.PolicyComServerController.Post*
  commentId: Overload:Toems_ApplicationApi.Controllers.PolicyComServerController.Post
  isExternal: true
  href: Toems_ApplicationApi.Controllers.PolicyComServerController.html#Toems_ApplicationApi.Controllers.PolicyComServerController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityPolicyComServer})
  name: Post
  nameWithType: PolicyComServerController.Post
  fullName: Toems_ApplicationApi.Controllers.PolicyComServerController.Post
- uid: System.Collections.Generic.List{Toems_Common.Entity.EntityPolicyComServer}
  commentId: T:System.Collections.Generic.List{Toems_Common.Entity.EntityPolicyComServer}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<EntityPolicyComServer>
  nameWithType: List<EntityPolicyComServer>
  fullName: System.Collections.Generic.List<Toems_Common.Entity.EntityPolicyComServer>
  nameWithType.vb: List(Of EntityPolicyComServer)
  fullName.vb: System.Collections.Generic.List(Of Toems_Common.Entity.EntityPolicyComServer)
  name.vb: List(Of EntityPolicyComServer)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Toems_Common.Entity.EntityPolicyComServer
    name: EntityPolicyComServer
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Toems_Common.Entity.EntityPolicyComServer
    name: EntityPolicyComServer
    isExternal: true
  - name: )
- uid: Toems_Common.Dto.DtoActionResult
  isExternal: true
  name: DtoActionResult
  nameWithType: DtoActionResult
  fullName: Toems_Common.Dto.DtoActionResult
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Toems_ApplicationApi.Controllers.PolicyComServerController.Delete*
  commentId: Overload:Toems_ApplicationApi.Controllers.PolicyComServerController.Delete
  isExternal: true
  href: Toems_ApplicationApi.Controllers.PolicyComServerController.html#Toems_ApplicationApi.Controllers.PolicyComServerController.Delete(System.Int32)
  name: Delete
  nameWithType: PolicyComServerController.Delete
  fullName: Toems_ApplicationApi.Controllers.PolicyComServerController.Delete
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
