### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
  commentId: T:Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
  id: CustomAuthAttribute
  parent: Toems_ApplicationApi.Controllers.Authorization
  children:
  - Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
  - Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.OnAuthorization(System.Web.Http.Controllers.HttpActionContext)
  - Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.Permission
  langs:
  - csharp
  - vb
  name: CustomAuthAttribute
  nameWithType: CustomAuthAttribute
  fullName: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers.Authorization
  syntax:
    content: 'public class CustomAuthAttribute : AuthorizeAttribute'
    content.vb: Public Class CustomAuthAttribute Inherits AuthorizeAttribute
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.OnAuthorization(System.Web.Http.Controllers.HttpActionContext)
  commentId: M:Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.OnAuthorization(System.Web.Http.Controllers.HttpActionContext)
  id: OnAuthorization(System.Web.Http.Controllers.HttpActionContext)
  parent: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
  langs:
  - csharp
  - vb
  name: OnAuthorization(HttpActionContext)
  nameWithType: CustomAuthAttribute.OnAuthorization(HttpActionContext)
  fullName: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.OnAuthorization(System.Web.Http.Controllers.HttpActionContext)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers.Authorization
  example: []
  syntax:
    content: public override void OnAuthorization(HttpActionContext actionContext)
    parameters:
    - id: actionContext
      type: System.Web.Http.Controllers.HttpActionContext
    content.vb: Public Overrides Sub OnAuthorization(actionContext As HttpActionContext)
  overload: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.OnAuthorization*
- uid: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
  commentId: M:Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
  langs:
  - csharp
  - vb
  name: CustomAuthAttribute()
  nameWithType: CustomAuthAttribute.CustomAuthAttribute()
  fullName: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.CustomAuthAttribute()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers.Authorization
  syntax:
    content: public CustomAuthAttribute()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor*
  nameWithType.vb: CustomAuthAttribute.New()
  fullName.vb: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.New()
  name.vb: New()
- uid: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.Permission
  commentId: P:Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.Permission
  id: Permission
  parent: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
  langs:
  - csharp
  - vb
  name: Permission
  nameWithType: CustomAuthAttribute.Permission
  fullName: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.Permission
  type: Property
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers.Authorization
  syntax:
    content: public string Permission { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Permission As String
  overload: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.Permission*
references:
- uid: Toems_ApplicationApi.Controllers.Authorization
  commentId: N:Toems_ApplicationApi.Controllers.Authorization
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers.Authorization
  nameWithType: Toems_ApplicationApi.Controllers.Authorization
  fullName: Toems_ApplicationApi.Controllers.Authorization
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers.Authorization
    name: Authorization
    isExternal: true
    href: Toems_ApplicationApi.Controllers.Authorization.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers.Authorization
    name: Authorization
    isExternal: true
    href: Toems_ApplicationApi.Controllers.Authorization.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.OnAuthorization*
  commentId: Overload:Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.OnAuthorization
  isExternal: true
  href: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.html#Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.OnAuthorization(System.Web.Http.Controllers.HttpActionContext)
  name: OnAuthorization
  nameWithType: CustomAuthAttribute.OnAuthorization
  fullName: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.OnAuthorization
- uid: System.Web.Http.Controllers.HttpActionContext
  isExternal: true
  name: HttpActionContext
  nameWithType: HttpActionContext
  fullName: System.Web.Http.Controllers.HttpActionContext
- uid: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor*
  commentId: Overload:Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
  isExternal: true
  href: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.html#Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
  name: CustomAuthAttribute
  nameWithType: CustomAuthAttribute.CustomAuthAttribute
  fullName: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.CustomAuthAttribute
  nameWithType.vb: CustomAuthAttribute.New
  fullName.vb: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.New
  name.vb: New
- uid: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.Permission*
  commentId: Overload:Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.Permission
  isExternal: true
  href: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.html#Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.Permission
  name: Permission
  nameWithType: CustomAuthAttribute.Permission
  fullName: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.Permission
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
