### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.Authorization
  commentId: N:Toems_ApplicationApi.Controllers.Authorization
  id: Toems_ApplicationApi.Controllers.Authorization
  children:
  - Toems_ApplicationApi.Controllers.Authorization.ComputerAuthAttribute
  - Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
  - Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute
  - Toems_ApplicationApi.Controllers.Authorization.ImageAuthAttribute
  langs:
  - csharp
  - vb
  name: Toems_ApplicationApi.Controllers.Authorization
  nameWithType: Toems_ApplicationApi.Controllers.Authorization
  fullName: Toems_ApplicationApi.Controllers.Authorization
  type: Namespace
  assemblies:
  - Toems-ApplicationApi
references:
- uid: Toems_ApplicationApi.Controllers.Authorization.ComputerAuthAttribute
  commentId: T:Toems_ApplicationApi.Controllers.Authorization.ComputerAuthAttribute
  parent: Toems_ApplicationApi.Controllers.Authorization
  isExternal: true
  href: Toems_ApplicationApi.Controllers.Authorization.ComputerAuthAttribute.html
  name: ComputerAuthAttribute
  nameWithType: ComputerAuthAttribute
  fullName: Toems_ApplicationApi.Controllers.Authorization.ComputerAuthAttribute
- uid: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute
  commentId: T:Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute
  parent: Toems_ApplicationApi.Controllers.Authorization
  isExternal: true
  href: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute.html
  name: GroupAuthAttribute
  nameWithType: GroupAuthAttribute
  fullName: Toems_ApplicationApi.Controllers.Authorization.GroupAuthAttribute
- uid: Toems_ApplicationApi.Controllers.Authorization.ImageAuthAttribute
  commentId: T:Toems_ApplicationApi.Controllers.Authorization.ImageAuthAttribute
  parent: Toems_ApplicationApi.Controllers.Authorization
  isExternal: true
  href: Toems_ApplicationApi.Controllers.Authorization.ImageAuthAttribute.html
  name: ImageAuthAttribute
  nameWithType: ImageAuthAttribute
  fullName: Toems_ApplicationApi.Controllers.Authorization.ImageAuthAttribute
- uid: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
  commentId: T:Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
  parent: Toems_ApplicationApi.Controllers.Authorization
  isExternal: true
  href: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.html
  name: CustomAuthAttribute
  nameWithType: CustomAuthAttribute
  fullName: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
- uid: Toems_ApplicationApi.Controllers.Authorization
  commentId: N:Toems_ApplicationApi.Controllers.Authorization
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers.Authorization
  nameWithType: Toems_ApplicationApi.Controllers.Authorization
  fullName: Toems_ApplicationApi.Controllers.Authorization
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers.Authorization
    name: Authorization
    isExternal: true
    href: Toems_ApplicationApi.Controllers.Authorization.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers.Authorization
    name: Authorization
    isExternal: true
    href: Toems_ApplicationApi.Controllers.Authorization.html
