### YamlMime:ManagedReference
items:
- uid: Toems_ApplicationApi.Controllers.ModuleCategoryController
  commentId: T:Toems_ApplicationApi.Controllers.ModuleCategoryController
  id: ModuleCategoryController
  parent: Toems_ApplicationApi.Controllers
  children:
  - Toems_ApplicationApi.Controllers.ModuleCategoryController.#ctor
  - Toems_ApplicationApi.Controllers.ModuleCategoryController.Delete(System.String)
  - Toems_ApplicationApi.Controllers.ModuleCategoryController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityModuleCategory})
  langs:
  - csharp
  - vb
  name: ModuleCategoryController
  nameWithType: ModuleCategoryController
  fullName: Toems_ApplicationApi.Controllers.ModuleCategoryController
  type: Class
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: 'public class ModuleCategoryController : ApiController'
    content.vb: Public Class ModuleCategoryController Inherits ApiController
  inheritance:
  - System.Object
- uid: Toems_ApplicationApi.Controllers.ModuleCategoryController.#ctor
  commentId: M:Toems_ApplicationApi.Controllers.ModuleCategoryController.#ctor
  id: '#ctor'
  parent: Toems_ApplicationApi.Controllers.ModuleCategoryController
  langs:
  - csharp
  - vb
  name: ModuleCategoryController()
  nameWithType: ModuleCategoryController.ModuleCategoryController()
  fullName: Toems_ApplicationApi.Controllers.ModuleCategoryController.ModuleCategoryController()
  type: Constructor
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: public ModuleCategoryController()
    content.vb: Public Sub New()
  overload: Toems_ApplicationApi.Controllers.ModuleCategoryController.#ctor*
  nameWithType.vb: ModuleCategoryController.New()
  fullName.vb: Toems_ApplicationApi.Controllers.ModuleCategoryController.New()
  name.vb: New()
- uid: Toems_ApplicationApi.Controllers.ModuleCategoryController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityModuleCategory})
  commentId: M:Toems_ApplicationApi.Controllers.ModuleCategoryController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityModuleCategory})
  id: Post(System.Collections.Generic.List{Toems_Common.Entity.EntityModuleCategory})
  parent: Toems_ApplicationApi.Controllers.ModuleCategoryController
  langs:
  - csharp
  - vb
  name: Post(List<EntityModuleCategory>)
  nameWithType: ModuleCategoryController.Post(List<EntityModuleCategory>)
  fullName: Toems_ApplicationApi.Controllers.ModuleCategoryController.Post(System.Collections.Generic.List<Toems_Common.Entity.EntityModuleCategory>)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "moduleUpdate")]

      public DtoActionResult Post(List<EntityModuleCategory> moduleCategories)
    parameters:
    - id: moduleCategories
      type: System.Collections.Generic.List{Toems_Common.Entity.EntityModuleCategory}
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="moduleUpdate")>

      Public Function Post(moduleCategories As List(Of EntityModuleCategory)) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.ModuleCategoryController.Post*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: moduleUpdate
  nameWithType.vb: ModuleCategoryController.Post(List(Of EntityModuleCategory))
  fullName.vb: Toems_ApplicationApi.Controllers.ModuleCategoryController.Post(System.Collections.Generic.List(Of Toems_Common.Entity.EntityModuleCategory))
  name.vb: Post(List(Of EntityModuleCategory))
- uid: Toems_ApplicationApi.Controllers.ModuleCategoryController.Delete(System.String)
  commentId: M:Toems_ApplicationApi.Controllers.ModuleCategoryController.Delete(System.String)
  id: Delete(System.String)
  parent: Toems_ApplicationApi.Controllers.ModuleCategoryController
  langs:
  - csharp
  - vb
  name: Delete(string)
  nameWithType: ModuleCategoryController.Delete(string)
  fullName: Toems_ApplicationApi.Controllers.ModuleCategoryController.Delete(string)
  type: Method
  assemblies:
  - Toems-ApplicationApi
  namespace: Toems_ApplicationApi.Controllers
  syntax:
    content: >-
      [CustomAuth(Permission = "moduleUpdate")]

      public DtoActionResult Delete(string moduleGuid)
    parameters:
    - id: moduleGuid
      type: System.String
    return:
      type: Toems_Common.Dto.DtoActionResult
    content.vb: >-
      <CustomAuth(Permission:="moduleUpdate")>

      Public Function Delete(moduleGuid As String) As DtoActionResult
  overload: Toems_ApplicationApi.Controllers.ModuleCategoryController.Delete*
  attributes:
  - type: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute
    ctor: Toems_ApplicationApi.Controllers.Authorization.CustomAuthAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Permission
      type: System.String
      value: moduleUpdate
  nameWithType.vb: ModuleCategoryController.Delete(String)
  fullName.vb: Toems_ApplicationApi.Controllers.ModuleCategoryController.Delete(String)
  name.vb: Delete(String)
references:
- uid: Toems_ApplicationApi.Controllers
  commentId: N:Toems_ApplicationApi.Controllers
  isExternal: true
  href: Toems_ApplicationApi.html
  name: Toems_ApplicationApi.Controllers
  nameWithType: Toems_ApplicationApi.Controllers
  fullName: Toems_ApplicationApi.Controllers
  spec.csharp:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
  spec.vb:
  - uid: Toems_ApplicationApi
    name: Toems_ApplicationApi
    isExternal: true
    href: Toems_ApplicationApi.html
  - name: .
  - uid: Toems_ApplicationApi.Controllers
    name: Controllers
    isExternal: true
    href: Toems_ApplicationApi.Controllers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Toems_ApplicationApi.Controllers.ModuleCategoryController.#ctor*
  commentId: Overload:Toems_ApplicationApi.Controllers.ModuleCategoryController.#ctor
  isExternal: true
  href: Toems_ApplicationApi.Controllers.ModuleCategoryController.html#Toems_ApplicationApi.Controllers.ModuleCategoryController.#ctor
  name: ModuleCategoryController
  nameWithType: ModuleCategoryController.ModuleCategoryController
  fullName: Toems_ApplicationApi.Controllers.ModuleCategoryController.ModuleCategoryController
  nameWithType.vb: ModuleCategoryController.New
  fullName.vb: Toems_ApplicationApi.Controllers.ModuleCategoryController.New
  name.vb: New
- uid: Toems_ApplicationApi.Controllers.ModuleCategoryController.Post*
  commentId: Overload:Toems_ApplicationApi.Controllers.ModuleCategoryController.Post
  isExternal: true
  href: Toems_ApplicationApi.Controllers.ModuleCategoryController.html#Toems_ApplicationApi.Controllers.ModuleCategoryController.Post(System.Collections.Generic.List{Toems_Common.Entity.EntityModuleCategory})
  name: Post
  nameWithType: ModuleCategoryController.Post
  fullName: Toems_ApplicationApi.Controllers.ModuleCategoryController.Post
- uid: System.Collections.Generic.List{Toems_Common.Entity.EntityModuleCategory}
  commentId: T:System.Collections.Generic.List{Toems_Common.Entity.EntityModuleCategory}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<EntityModuleCategory>
  nameWithType: List<EntityModuleCategory>
  fullName: System.Collections.Generic.List<Toems_Common.Entity.EntityModuleCategory>
  nameWithType.vb: List(Of EntityModuleCategory)
  fullName.vb: System.Collections.Generic.List(Of Toems_Common.Entity.EntityModuleCategory)
  name.vb: List(Of EntityModuleCategory)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Toems_Common.Entity.EntityModuleCategory
    name: EntityModuleCategory
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Toems_Common.Entity.EntityModuleCategory
    name: EntityModuleCategory
    isExternal: true
  - name: )
- uid: Toems_Common.Dto.DtoActionResult
  isExternal: true
  name: DtoActionResult
  nameWithType: DtoActionResult
  fullName: Toems_Common.Dto.DtoActionResult
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Toems_ApplicationApi.Controllers.ModuleCategoryController.Delete*
  commentId: Overload:Toems_ApplicationApi.Controllers.ModuleCategoryController.Delete
  isExternal: true
  href: Toems_ApplicationApi.Controllers.ModuleCategoryController.html#Toems_ApplicationApi.Controllers.ModuleCategoryController.Delete(System.String)
  name: Delete
  nameWithType: ModuleCategoryController.Delete
  fullName: Toems_ApplicationApi.Controllers.ModuleCategoryController.Delete
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
